government_map = {
    "aristocratic_monarchy": "monarchy",
    "despotic_monarchy": "monarchy",
    "stratocratic_monarchy": "monarchy",
    "aristocratic_republic": "republic",
    "plutocratic_republic": "republic",
    "oligarchic_republic": "republic",
    "democratic_republic": "republic",
    "theocratic_monarchy": "theocracy",
    "tribal_kingdom": "tribe",
    "tribal_federation": "tribe",
    "tribal_chiefdom": "tribe",
}

# Map IR culture groups to base-game languages for court language assignment.
# These are best-effort mappings to existing EU5 language identifiers.
ir_culture_group_language_map = {
    "ir_hellenic_g": "greek_language",
    "ir_latin_g": "latin_language",
    "ir_illyrian_group_g": "albanian_language",
    "ir_dacia_group_g": "greek_language",
    "ir_baltic_g": "baltic_language",
    "ir_germanic_g": "german_language",
    "ir_britannic_g": "brythonic_language",
    "ir_gaelic_g": "gaelic_language",
    "ir_gallic_g": "brythonic_language",
    "ir_belgae_group_g": "brythonic_language",
    "ir_celto_pannonian_group_g": "brythonic_language",
    "ir_celt_iberia_g": "brythonic_language",
    "ir_iberia_g": "basque_language",
    "ir_scythia_g": "alanic_language",
    "ir_persia_g": "persian_language",
    "ir_bactrian_g": "persian_language",
    "ir_aryan_g": "sanskrit_language",
    "ir_pracyan_g": "bihari_language",
    "ir_indian_g": "sanskrit_language",
    "ir_tibetan_g": "tibetan_language",
    "ir_anatolian_g": "greek_language",
    "ir_caucasian_g": "georgian_language",
    "ir_east_levantine_g": "aramaic_language",
    "ir_west_levantine_g": "aramaic_language",
    "ir_south_levantine_g": "aramaic_language",
    "ir_north_african_g": "coptic_language",
    "ir_numidian_g": "tamazight_language",
    "ir_meroitic_group_g": "nubian_language",
    "ir_aksumite_group_g": "ethiopic_language",
    "ir_proto_european_g": "latin_language",
}

# Per-culture overrides when a specific culture should use a more precise language.
ir_culture_language_overrides = {
    "ir_hebrew": "hebrew_language",
    "ir_armenian": "armenian_language",
    "ir_nabatean": "aramaic_language",
    "ir_kannadan": "kannada_language",
    "ir_telugu": "telugu_language",
    "ir_saurashtran": "gujarati_language",
    "ir_maharashtran": "marathi_language",
    "ir_vidharban": "marathi_language",
    "ir_lankan": "sinhala_language",
    "ir_sindhi": "sindhi_language",
    "ir_gandhari": "sanskrit_language",
    "ir_dardic": "sanskrit_language",
    "ir_shauraseni": "bihari_language",
    "ir_avanti": "bihari_language",
    "ir_kalingan": "oriya_language",
    "ir_kamarupi": "brahmaputran_language",
    "ir_bangli": "bengali_language",
    "ir_himalayan": "west_himalayic_language",
    "ir_atavi": "munda_language",
    "ir_magadhi": "bihari_language",
}
