government_map = {
    "aristocratic_monarchy": "monarchy",
    "despotic_monarchy": "monarchy",
    "stratocratic_monarchy": "monarchy",
    "aristocratic_republic": "republic",
    "plutocratic_republic": "republic",
    "oligarchic_republic": "republic",
    "democratic_republic": "republic",
    "punic_republic": "republic",
    "spartan_monarchy": "monarchy",
    "plutocratic_monarchy": "monarchy",
    "theocratic_republic": "theocracy",
    "theocratic_monarchy": "theocracy",
    "tribal_kingdom": "tribe",
    "tribal_federation": "tribe",
    "tribal_chiefdom": "tribe",
}

# Map IR culture groups to IU language IDs (304 BC best-effort).
ir_culture_group_language_map = {
    "ir_aksumite_group_g": "ir_geez_lang",
    "ir_anatolian_g": "ir_anatolian_lang",
    "ir_aryan_g": "ir_sanskrit_lang",
    "ir_bactrian_g": "ir_bactrian_lang",
    "ir_baltic_g": "ir_proto_baltic_lang",
    "ir_belgae_group_g": "ir_belgic_lang",
    "ir_britannic_g": "ir_brittonic_lang",
    "ir_caucasian_g": "ir_kartvelian_lang",
    "ir_celt_iberia_g": "ir_celtiberian_lang",
    "ir_celto_pannonian_group_g": "ir_pannonian_celtic_lang",
    "ir_dacia_group_g": "ir_dacian_lang",
    "ir_east_levantine_g": "ir_aramaic_lang",
    "ir_gaelic_g": "ir_goidelic_lang",
    "ir_gallic_g": "ir_gaulish_lang",
    "ir_germanic_g": "ir_proto_germanic_lang",
    "ir_hellenic_g": "ir_greek_lang",
    "ir_iberia_g": "ir_iberian_lang",
    "ir_illyrian_group_g": "ir_illyrian_lang",
    "ir_indian_g": "ir_prakrit_lang",
    "ir_latin_g": "ir_latin_lang",
    "ir_meroitic_group_g": "ir_meroitic_lang",
    "ir_north_african_g": "ir_egyptian_lang",
    "ir_numidian_g": "ir_numidian_lang",
    "ir_persia_g": "ir_persian_lang",
    "ir_pracyan_g": "ir_magadhan_prakrit_lang",
    "ir_proto_european_g": "ir_proto_european_lang",
    "ir_scythia_g": "ir_scythian_lang",
    "ir_south_levantine_g": "ir_hebrew_lang",
    "ir_tibetan_g": "ir_tibetic_lang",
    "ir_west_levantine_g": "ir_phoenician_lang",
    "ir_chinese_g": "ir_old_chinese_lang",
    "ir_fezzani_g": "ir_garamantian_lang",
    "ir_finnic_group_g": "ir_proto_finnic_lang",
    "ir_nilotic_group_g": "ir_nilotic_lang",
    "ir_pu_g": "ir_punic_lang",
    "ir_scythian_east_g": "ir_saka_lang",
    "ir_south_arabian_g": "ir_old_south_arabian_lang",
    "ir_thrace_group_g": "ir_thracian_lang",
}

# Languages that should be treated as dialects of a parent language.
# When assigned to cultures, they will be mapped to the parent language.
ir_language_dialect_parent_map = {
    # Greek dialects
    "ir_attic_lang": "ir_greek_lang",
    "ir_ionic_lang": "ir_greek_lang",
    "ir_doric_lang": "ir_greek_lang",
    "ir_aeolic_lang": "ir_greek_lang",
    "ir_arcado_cypriot_lang": "ir_greek_lang",
    "ir_macedonian_lang": "ir_greek_lang",
    "ir_pamphylian_lang": "ir_greek_lang",
    "ir_koine_lang": "ir_greek_lang",
    # Brittonic dialects
    "ir_south_brittonic_lang": "ir_brittonic_lang",
    "ir_cumbric_lang": "ir_brittonic_lang",
    "ir_pictish_lang": "ir_brittonic_lang",
    "ir_armorican_lang": "ir_brittonic_lang",
    # Belgic dialects
    "ir_belgic_north_lang": "ir_belgic_lang",
    "ir_belgic_coastal_lang": "ir_belgic_lang",
    # Gaulish regional dialects
    "ir_central_gaulish_lang": "ir_gaulish_lang",
    "ir_eastern_gaulish_lang": "ir_gaulish_lang",
    "ir_narbonese_lang": "ir_gaulish_lang",
    "ir_helvetian_lang": "ir_gaulish_lang",
    # Italic regional dialects
    "ir_venetic_lang": "ir_latin_lang",
    "ir_ligurian_lang": "ir_latin_lang",
    "ir_rhaetian_lang": "ir_latin_lang",
}

# Base language for each IU language (used for deriving distinct colors)
ir_language_base_color_map = {
    "ir_greek_lang": "greek_language",
    "ir_attic_lang": "greek_language",
    "ir_ionic_lang": "greek_language",
    "ir_aeolic_lang": "greek_language",
    "ir_doric_lang": "greek_language",
    "ir_arcado_cypriot_lang": "greek_language",
    "ir_macedonian_lang": "greek_language",
    "ir_pamphylian_lang": "greek_language",
    "ir_koine_lang": "greek_language",
    "ir_lycian_lang": "greek_language",
    "ir_lydian_lang": "greek_language",
    "ir_phrygian_lang": "greek_language",
    "ir_cappadocian_lang": "greek_language",
    "ir_pisidian_lang": "greek_language",
    "ir_isaurian_lang": "greek_language",
    "ir_paphlagonian_lang": "greek_language",
    "ir_cilician_lang": "greek_language",
    "ir_mysian_lang": "greek_language",
    "ir_cabalian_lang": "greek_language",
    "ir_carian_lang": "greek_language",
    "ir_latin_lang": "latin_language",
    "ir_venetic_lang": "latin_language",
    "ir_ligurian_lang": "latin_language",
    "ir_rhaetian_lang": "latin_language",
    "ir_proto_baltic_lang": "baltic_language",
    "ir_aestian_lang": "baltic_language",
    "ir_neuric_lang": "baltic_language",
    "ir_proto_germanic_lang": "german_language",
    "ir_suebian_lang": "german_language",
    "ir_saxon_lang": "german_language",
    "ir_gothic_lang": "german_language",
    "ir_north_germanic_lang": "german_language",
    "ir_mordvin_lang": "mordvinic_language",
    "ir_volgaic_lang": "mari_language",
    "ir_brittonic_lang": "brythonic_language",
    "ir_cumbric_lang": "brythonic_language",
    "ir_pictish_lang": "brythonic_language",
    "ir_goidelic_lang": "gaelic_language",
    "ir_gaulish_lang": "brythonic_language",
    "ir_belgic_lang": "brythonic_language",
    "ir_belgic_north_lang": "brythonic_language",
    "ir_belgic_coastal_lang": "brythonic_language",
    "ir_south_brittonic_lang": "brythonic_language",
    "ir_pannonian_celtic_lang": "brythonic_language",
    "ir_celtiberian_lang": "brythonic_language",
    "ir_lusitanian_lang": "brythonic_language",
    "ir_lepontic_lang": "brythonic_language",
    "ir_armorican_lang": "brythonic_language",
    "ir_helvetian_lang": "brythonic_language",
    "ir_gallaecian_lang": "brythonic_language",
    "ir_central_gaulish_lang": "brythonic_language",
    "ir_eastern_gaulish_lang": "brythonic_language",
    "ir_narbonese_lang": "brythonic_language",
    "ir_iberian_lang": "basque_language",
    "ir_aquitanian_lang": "basque_language",
    "ir_turdetanian_lang": "basque_language",
    "ir_messapic_lang": "albanian_language",
    "ir_tartessian_lang": "basque_language",
    "ir_edetanian_lang": "basque_language",
    "ir_lacetanian_lang": "basque_language",
    "ir_gaetulian_lang": "tamazight_language",
    "ir_canarian_lang": "tamazight_language",
    "ir_mauritanian_lang": "tamazight_language",
    "ir_illyrian_lang": "albanian_language",
    "ir_kartvelian_lang": "georgian_language",
    "ir_albanian_caucasian_lang": "georgian_language",
    "ir_north_caucasian_lang": "georgian_language",
    "ir_armenian_lang": "armenian_language",
    "ir_aramaic_lang": "aramaic_language",
    "ir_assyrian_lang": "aramaic_language",
    "ir_babylonian_lang": "aramaic_language",
    "ir_nabatean_lang": "aramaic_language",
    "ir_old_north_arabian_lang": "aramaic_language",
    "ir_phoenician_lang": "aramaic_language",
    "ir_hebrew_lang": "hebrew_language",
    "ir_himjaritic_lang": "aramaic_language",
    "ir_egyptian_lang": "coptic_language",
    "ir_blemmye_lang": "nubian_language",
    "ir_puntic_lang": "ethiopic_language",
    "ir_nubian_lang": "nubian_language",
    "ir_dinka_lang": "dinka_language",
    "ir_persian_lang": "persian_language",
    "ir_bactrian_lang": "persian_language",
    "ir_parthian_lang": "persian_language",
    "ir_median_lang": "persian_language",
    "ir_elamite_lang": "persian_language",
    "ir_sogdian_lang": "persian_language",
    "ir_alanic_lang": "persian_language",
    "ir_sarmatian_lang": "persian_language",
    "ir_massagetaean_lang": "persian_language",
    "ir_khotanese_lang": "persian_language",
    "ir_tocharian_lang": "persian_language",
    "ir_yuezhi_lang": "persian_language",
    "ir_wusun_lang": "persian_language",
    "ir_sanskrit_lang": "sanskrit_language",
    "ir_sindhi_lang": "sindhi_language",
    "ir_bengali_lang": "bengali_language",
    "ir_oriya_lang": "oriya_language",
    "ir_kamarupi_lang": "kamarupi_language",
    "ir_himalayan_lang": "west_himalayic_language",
    "ir_kannada_lang": "kannada_language",
    "ir_telugu_lang": "telugu_language",
    "ir_tamil_lang": "tamil_language",
    "ir_gandhari_lang": "sanskrit_language",
    "ir_old_chinese_lang": "classical_chinese_language",
    "ir_tibetic_lang": "tibetan_language",
    "ir_garamantian_lang": "tamazight_language",
    "ir_nilotic_lang": "dinka_language",
    "ir_proto_finnic_lang": "finnish_language",
    "ir_old_south_arabian_lang": "south_arabic_language",
    "ir_punic_lang": "aramaic_language",
}

# Base-game languages to copy data from when possible (for IU language blocks).
ir_culture_group_base_language_map = {
    "ir_hellenic_g": "greek_language",
    "ir_latin_g": "latin_language",
    "ir_illyrian_group_g": "albanian_language",
    "ir_dacia_group_g": "greek_language",
    "ir_baltic_g": "baltic_language",
    "ir_germanic_g": "german_language",
    "ir_britannic_g": "brythonic_language",
    "ir_gaelic_g": "gaelic_language",
    "ir_gallic_g": "brythonic_language",
    "ir_belgae_group_g": "brythonic_language",
    "ir_celto_pannonian_group_g": "brythonic_language",
    "ir_celt_iberia_g": "brythonic_language",
    "ir_iberia_g": "basque_language",
    "ir_scythia_g": "alanic_language",
    "ir_persia_g": "persian_language",
    "ir_bactrian_g": "persian_language",
    "ir_aryan_g": "sanskrit_language",
    "ir_pracyan_g": "bihari_language",
    "ir_indian_g": "sanskrit_language",
    "ir_tibetan_g": "tibetan_language",
    "ir_anatolian_g": "greek_language",
    "ir_caucasian_g": "georgian_language",
    "ir_east_levantine_g": "aramaic_language",
    "ir_west_levantine_g": "aramaic_language",
    "ir_south_levantine_g": "aramaic_language",
    "ir_north_african_g": "coptic_language",
    "ir_numidian_g": "tamazight_language",
    "ir_meroitic_group_g": "nubian_language",
    "ir_aksumite_group_g": "ethiopic_language",
    "ir_proto_european_g": "latin_language",
}

# Map IR culture groups to EU5 graphical culture tags for culture gfx assignment.
# These are best-effort mappings to existing EU5 graphical culture identifiers.
ir_culture_group_graphical_map = {
    "ir_hellenic_g": [
        "greek_gfx",
        "east_mediterranean_gfx",
        "mediterranean_gfx",
        "european_gfx",
    ],
    "ir_latin_g": [
        "north_italian_gfx",
        "south_italian_gfx",
        "west_mediterranean_gfx",
        "mediterranean_gfx",
        "european_gfx",
    ],
    "ir_illyrian_group_g": [
        "south_slavic_gfx",
        "romanian_gfx",
        "mediterranean_gfx",
        "european_gfx",
    ],
    "ir_dacia_group_g": ["romanian_gfx", "eastern_european_gfx", "european_gfx"],
    "ir_baltic_g": ["baltic_gfx", "eastern_european_gfx", "european_gfx"],
    "ir_germanic_g": [
        "german_gfx",
        "north_german_gfx",
        "western_european_gfx",
        "european_gfx",
    ],
    "ir_britannic_g": ["western_european_gfx", "european_gfx"],
    "ir_gaelic_g": ["western_european_gfx", "european_gfx"],
    "ir_gallic_g": ["western_european_gfx", "european_gfx"],
    "ir_belgae_group_g": ["western_european_gfx", "european_gfx"],
    "ir_celto_pannonian_group_g": [
        "western_european_gfx",
        "eastern_european_gfx",
        "european_gfx",
    ],
    "ir_celt_iberia_g": [
        "castilian_gfx",
        "portuguese_gfx",
        "west_mediterranean_gfx",
        "mediterranean_gfx",
        "european_gfx",
    ],
    "ir_iberia_g": [
        "castilian_gfx",
        "portuguese_gfx",
        "basque_gfx",
        "west_mediterranean_gfx",
        "mediterranean_gfx",
        "european_gfx",
    ],
    "ir_scythia_g": ["central_asian_gfx", "turkic_gfx", "mongol_gfx", "east_asian_gfx"],
    "ir_persia_g": ["persian_gfx", "persianate_gfx", "middle_east_gfx"],
    "ir_bactrian_g": [
        "persianate_gfx",
        "central_asian_gfx",
        "persian_gfx",
        "middle_east_gfx",
    ],
    "ir_aryan_g": ["persianate_gfx", "indian_gfx"],
    "ir_pracyan_g": ["persianate_gfx", "indian_gfx"],
    "ir_indian_g": ["persianate_gfx", "indian_gfx"],
    "ir_tibetan_g": ["tibetan_gfx", "east_asian_gfx"],
    "ir_anatolian_g": [
        "turkish_gfx",
        "east_mediterranean_gfx",
        "mediterranean_gfx",
        "middle_east_gfx",
    ],
    "ir_caucasian_g": ["caucasian_gfx", "middle_east_gfx"],
    "ir_east_levantine_g": ["levantine_gfx", "middle_east_gfx"],
    "ir_west_levantine_g": [
        "levantine_gfx",
        "east_mediterranean_gfx",
        "maghrebi_gfx",
        "middle_east_gfx",
    ],
    "ir_south_levantine_g": ["arabian_gfx", "levantine_gfx", "middle_east_gfx"],
    "ir_north_african_g": ["egyptian_gfx", "maghrebi_gfx", "african_gfx"],
    "ir_numidian_g": ["amazigh_gfx", "maghrebi_gfx", "african_gfx"],
    "ir_meroitic_group_g": ["egyptian_gfx", "east_african_gfx", "african_gfx"],
    "ir_aksumite_group_g": ["east_african_gfx", "african_gfx"],
    "ir_proto_european_g": ["western_european_gfx", "european_gfx"],
    "ir_nilotic_group_g": ["east_african_gfx", "african_gfx"],
    "ir_pu_g": ["levantine_gfx", "maghrebi_gfx", "middle_east_gfx"],
    "ir_fezzani_g": ["amazigh_gfx", "maghrebi_gfx", "african_gfx"],
    "ir_finnic_group_g": ["eastern_european_gfx", "european_gfx"],
    "ir_scythian_east_g": ["central_asian_gfx", "middle_east_gfx"],
    "ir_south_arabian_g": ["arabian_gfx", "middle_east_gfx"],
    "ir_thrace_group_g": [
        "greek_gfx",
        "east_mediterranean_gfx",
        "mediterranean_gfx",
        "eastern_european_gfx",
        "european_gfx",
    ],
    "ir_chinese_g": ["chinese_gfx", "east_asian_gfx"],
}

# Per-culture overrides for languages.
ir_culture_language_overrides = {
    # Italic group splits
    "ir_roman": "ir_latin_lang",
    "ir_venetic": "ir_venetic_lang",
    "ir_ligurian": "ir_ligurian_lang",
    "ir_etruscan": "ir_etruscan_lang",
    "ir_rhaetian": "ir_rhaetian_lang",
    "ir_umbrian": "ir_umbrian_lang",
    "ir_samnite": "ir_oscan_lang",
    "ir_lucanian": "ir_oscan_lang",
    "ir_bruttian": "ir_oscan_lang",
    "ir_siculian": "ir_siculian_lang",
    "ir_histrian": "ir_venetic_lang",
        # Britannic splits
    "ir_brigantic": "ir_cumbric_lang",
    "ir_parisian": "ir_cumbric_lang",
    "ir_votadinian": "ir_cumbric_lang",
    "ir_caledonian": "ir_pictish_lang",
    "ir_monapian": "ir_pictish_lang",
    "ir_taexalian": "ir_pictish_lang",
    "ir_ivernian": "ir_goidelic_lang",
    "ir_voluntian": "ir_goidelic_lang",
    "ir_britannic": "ir_south_brittonic_lang",
    "ir_cantian": "ir_south_brittonic_lang",
    "ir_trinovantian": "ir_south_brittonic_lang",
    "ir_coritani": "ir_south_brittonic_lang",
    "ir_iceni": "ir_south_brittonic_lang",
    "ir_dobunnian": "ir_south_brittonic_lang",
    "ir_durotrigan": "ir_south_brittonic_lang",
    "ir_dumnonian": "ir_south_brittonic_lang",
    "ir_damnonian": "ir_south_brittonic_lang",
    "ir_demetian": "ir_south_brittonic_lang",
    "ir_ordovitian": "ir_south_brittonic_lang",
    "ir_cornovian": "ir_south_brittonic_lang",
    # Iberian peninsula splits
    "ir_aquitani": "ir_aquitanian_lang",
    "ir_vasconian": "ir_aquitanian_lang",
    "ir_turdetanian": "ir_turdetanian_lang",
    "ir_turdulian": "ir_turdetanian_lang",
    "ir_lusitanian": "ir_lusitanian_lang",
    "ir_vettonian": "ir_lusitanian_lang",
    "ir_messapian": "ir_messapic_lang",
    # Iberian splits
    "ir_oretanian": "ir_tartessian_lang",
    "ir_bastetanian": "ir_tartessian_lang",
    "ir_contestanian": "ir_edetanian_lang",
    "ir_edetanian": "ir_edetanian_lang",
    "ir_ilercavonian": "ir_edetanian_lang",
    "ir_indiketian": "ir_lacetanian_lang",
    "ir_ausetanian": "ir_lacetanian_lang",
    "ir_lacetanian": "ir_lacetanian_lang",
    "ir_ilergetian": "ir_lacetanian_lang",
    # Celtiberia splits
    "ir_callaecian": "ir_gallaecian_lang",
    "ir_asturian": "ir_gallaecian_lang",
    "ir_cantabrian": "ir_gallaecian_lang",
    "ir_autrigonian": "ir_gallaecian_lang",
    "ir_caristian": "ir_gallaecian_lang",
    "ir_vardulian": "ir_gallaecian_lang",
    "ir_celtiberian": "ir_celtiberian_lang",
    "ir_celtician": "ir_celtiberian_lang",
    "ir_couneian": "ir_celtiberian_lang",
    "ir_carpetanian": "ir_celtiberian_lang",
    "ir_lobetanian": "ir_celtiberian_lang",
    "ir_oppidanian": "ir_celtiberian_lang",
    "ir_sedetanian": "ir_celtiberian_lang",
    "ir_vaccaeian": "ir_celtiberian_lang",
    "ir_elesycian": "ir_celtiberian_lang",
    # Maghreb splits
    "ir_gaetulian": "ir_gaetulian_lang",
    "ir_melanogaetulian": "ir_gaetulian_lang",
    "ir_canarian": "ir_canarian_lang",
    "ir_numidian": "ir_numidian_lang",
    "ir_massaesylian": "ir_numidian_lang",
    "ir_massylian": "ir_numidian_lang",
    "ir_socossian": "ir_numidian_lang",
    "ir_autolalean": "ir_mauritanian_lang",
    "ir_capariensian": "ir_mauritanian_lang",
    "ir_cetianian": "ir_mauritanian_lang",
    "ir_daphnitaean": "ir_mauritanian_lang",
    "ir_nectiberean": "ir_mauritanian_lang",
    "ir_nigirtean": "ir_mauritanian_lang",
    # Greek dialect splits
    "ir_athenian": "ir_attic_lang",
    "ir_ionian": "ir_ionic_lang",
    "ir_aegean": "ir_ionic_lang",
    "ir_euboean": "ir_ionic_lang",
    "ir_massalian": "ir_ionic_lang",
    "ir_aeolian": "ir_aeolic_lang",
    "ir_boeotian": "ir_aeolic_lang",
    "ir_thessalian": "ir_aeolic_lang",
    "ir_troan": "ir_aeolic_lang",
    "ir_arcadian": "ir_arcado_cypriot_lang",
    "ir_cypriot": "ir_arcado_cypriot_lang",
    "ir_argolian": "ir_doric_lang",
    "ir_achaean": "ir_doric_lang",
    "ir_peloponnesian": "ir_doric_lang",
    "ir_cretan": "ir_doric_lang",
    "ir_syracusan": "ir_doric_lang",
    "ir_italiotian": "ir_doric_lang",
    "ir_epirote": "ir_doric_lang",
    "ir_macedonian": "ir_macedonian_lang",
    "ir_aetolian": "ir_doric_lang",
    "ir_bosporan": "ir_koine_lang",
    "ir_cyrenaican": "ir_doric_lang",
    "ir_greco_pontic": "ir_koine_lang",
    "ir_greco_indian": "ir_koine_lang",
    "ir_hellenistic": "ir_koine_lang",
    "ir_pamphylian": "ir_pamphylian_lang",
    "ir_syriote": "ir_koine_lang",
    "ir_ciliciote": "ir_koine_lang",
    "ir_carian": "ir_carian_lang",
    "ir_enetoian": "ir_paphlagonian_lang",
    "ir_thracian": "ir_thracian_lang",
    # Anatolian splits
    "ir_lycian": "ir_lycian_lang",
    "ir_lydian": "ir_lydian_lang",
    "ir_phrygian": "ir_phrygian_lang",
    "ir_cappadocian": "ir_cappadocian_lang",
    "ir_cataonian": "ir_cappadocian_lang",
    "ir_lycaonian": "ir_cappadocian_lang",
    "ir_pisidian": "ir_pisidian_lang",
    "ir_isaurian": "ir_isaurian_lang",
    "ir_paphlagonian": "ir_paphlagonian_lang",
    "ir_cilician": "ir_cilician_lang",
    "ir_mysian": "ir_mysian_lang",
    "ir_cabalian": "ir_cabalian_lang",
    "ir_kennataian": "ir_cabalian_lang",
    "ir_lalasian": "ir_cabalian_lang",
    "ir_milyadian": "ir_cabalian_lang",
    "ir_morimenian": "ir_cabalian_lang",
    "ir_oroandian": "ir_cabalian_lang",
    # Gaul splits
    "ir_lepontic": "ir_lepontic_lang",
    # Belgae splits
    "ir_aduatacian": "ir_belgic_north_lang",
    "ir_belgae": "ir_belgic_north_lang",
    "ir_eburonian": "ir_belgic_north_lang",
    "ir_nervian": "ir_belgic_north_lang",
    "ir_bellovacian": "ir_belgic_coastal_lang",
    "ir_morinian": "ir_belgic_coastal_lang",
    "ir_veliocassian": "ir_belgic_coastal_lang",
    # Fezzani
    "ir_atarantian": "ir_garamantian_lang",
    "ir_atlantean": "ir_garamantian_lang",
    "ir_berber": "ir_garamantian_lang",
    "ir_garamantic": "ir_garamantian_lang",
    "ir_gyzantian": "ir_garamantian_lang",
    "ir_libyan": "ir_garamantian_lang",
    "ir_lotophagoi": "ir_garamantian_lang",
    "ir_macaean": "ir_garamantian_lang",
    "ir_nasamonian": "ir_garamantian_lang",
    "ir_phazani": "ir_garamantian_lang",
    "ir_psyllic": "ir_garamantian_lang",
    "ir_aremorican": "ir_armorican_lang",
    "ir_pictonian": "ir_armorican_lang",
    "ir_helvetian": "ir_helvetian_lang",
    "ir_noric": "ir_helvetian_lang",
    "ir_vindelician": "ir_helvetian_lang",
    "ir_boian": "ir_helvetian_lang",
    "ir_arverni": "ir_central_gaulish_lang",
    "ir_haedui": "ir_central_gaulish_lang",
    "ir_biturigan": "ir_central_gaulish_lang",
    "ir_carnuti": "ir_central_gaulish_lang",
    "ir_sennonian": "ir_central_gaulish_lang",
    "ir_aulercian": "ir_central_gaulish_lang",
    "ir_lemovician": "ir_central_gaulish_lang",
    "ir_santonian": "ir_central_gaulish_lang",
    "ir_allobrogian": "ir_eastern_gaulish_lang",
    "ir_carnian": "ir_eastern_gaulish_lang",
    "ir_cotinian": "ir_eastern_gaulish_lang",
    "ir_eravisci": "ir_eastern_gaulish_lang",
    "ir_letobician": "ir_eastern_gaulish_lang",
    "ir_celtic_pannonian": "ir_eastern_gaulish_lang",
    "ir_treverian": "ir_eastern_gaulish_lang",
    "ir_ubian": "ir_eastern_gaulish_lang",
    "ir_teurian": "ir_eastern_gaulish_lang",
    "ir_salluvian": "ir_narbonese_lang",
    "ir_volcae": "ir_narbonese_lang",
    # Specific cultures elsewhere
    "ir_armenian": "ir_armenian_lang",
    "ir_hebrew": "ir_hebrew_lang",
    "ir_assyrian": "ir_assyrian_lang",
    "ir_babylonian": "ir_babylonian_lang",
    "ir_carthaginian": "ir_punic_lang",
    "ir_nabatean": "ir_nabatean_lang",
    "ir_aramaic": "ir_aramaic_lang",
    "ir_cardukoi": "ir_assyrian_lang",
    "ir_dacian": "ir_dacian_lang",
    "ir_bactrian": "ir_bactrian_lang",
    "ir_egyptian": "ir_egyptian_lang",
    "ir_upper_egyptian": "ir_egyptian_lang",
    "ir_middle_egyptian": "ir_egyptian_lang",
    "ir_oasis_egyptian": "ir_egyptian_lang",
    "ir_gerrhan": "ir_old_north_arabian_lang",
    "ir_makan": "ir_old_north_arabian_lang",
    "ir_qedarite": "ir_old_north_arabian_lang",
    "ir_taif": "ir_old_north_arabian_lang",
    "ir_thamudi": "ir_old_north_arabian_lang",
    "ir_yamama": "ir_old_north_arabian_lang",
    # Arabia splits
    "ir_himjar": "ir_himjaritic_lang",
    # Persian/Iranian splits
    "ir_parthian": "ir_parthian_lang",
    "ir_median": "ir_median_lang",
    "ir_elamite": "ir_elamite_lang",
    "ir_sogdian": "ir_sogdian_lang",
    "ir_amardian": "ir_parthian_lang",
    "ir_cadusian": "ir_median_lang",
    "ir_hyrcanian": "ir_median_lang",
    "ir_utian": "ir_median_lang",
    "ir_cossian": "ir_elamite_lang",
    "ir_carmanian": "ir_persian_lang",
    "ir_gedrosian": "ir_persian_lang",
    "ir_pactyan": "ir_persian_lang",
    "ir_parecanian": "ir_persian_lang",
    "ir_pasargadi": "ir_persian_lang",
    "ir_sagartian": "ir_parthian_lang",
    "ir_sarangian": "ir_persian_lang",
    "ir_sattagydian": "ir_persian_lang",
    "ir_uxian": "ir_elamite_lang",
    # Illyrian splits
    "ir_dardanian": "ir_illyrian_lang",
    "ir_iapodian": "ir_illyrian_lang",
    "ir_liburnian": "ir_illyrian_lang",
    "ir_liburnian_culture": "ir_illyrian_lang",
    "ir_paeonian": "ir_illyrian_lang",
    "ir_pannonian": "ir_illyrian_lang",
    "ir_taulantian": "ir_illyrian_lang",
    "ir_abrian": "ir_illyrian_lang",
    "ir_catari": "ir_illyrian_lang",
    "ir_deraemestian": "ir_illyrian_lang",
    "ir_deurian": "ir_illyrian_lang",
    "ir_greco_illyrian": "ir_illyrian_lang",
    # Thrace/Dacia splits
    "ir_getian": "ir_dacian_lang",
    "ir_costoboci": "ir_dacian_lang",
    "ir_biephi": "ir_dacian_lang",
    "ir_buridavensi": "ir_dacian_lang",
    "ir_caucoensi": "ir_dacian_lang",
    "ir_harpii": "ir_dacian_lang",
    "ir_ratacensi": "ir_dacian_lang",
    "ir_bithynian": "ir_thracian_lang",
    "ir_mariandynian": "ir_thracian_lang",
    "ir_moesi": "ir_thracian_lang",
    "ir_odrysi": "ir_thracian_lang",
    "ir_triballoi": "ir_thracian_lang",
    # Proto-European splits
    "ir_corsian": "ir_proto_european_lang",
    "ir_nuragic": "ir_proto_european_lang",
    "ir_talaiotic": "ir_proto_european_lang",
    # Bactria/Central Asia splits
    "ir_margian": "ir_sogdian_lang",
    "ir_saka": "ir_saka_lang",
    "ir_tayuan": "ir_tocharian_lang",
    "ir_shule": "ir_tocharian_lang",
    # Caucasus splits
    "ir_ibero": "ir_kartvelian_lang",
    "ir_colchian": "ir_kartvelian_lang",
    "ir_lazi": "ir_kartvelian_lang",
    "ir_suani": "ir_kartvelian_lang",
    "ir_albanian": "ir_albanian_caucasian_lang",
    "ir_legian": "ir_albanian_caucasian_lang",
    "ir_caspian": "ir_albanian_caucasian_lang",
    "ir_abasgoi": "ir_north_caucasian_lang",
    "ir_gelaean": "ir_north_caucasian_lang",
    "ir_sindi": "ir_north_caucasian_lang",
    "ir_maeotian": "ir_north_caucasian_lang",
    "ir_sasperian": "ir_north_caucasian_lang",
    # Steppe splits
    "ir_alani": "ir_alanic_lang",
    "ir_sarmatian": "ir_sarmatian_lang",
    "ir_massagetaean": "ir_massagetaean_lang",
    "ir_khotanese": "ir_khotanese_lang",
    "ir_sakan": "ir_saka_lang",
    "ir_scythian": "ir_scythian_lang",
    "ir_siraci": "ir_sarmatian_lang",
    "ir_thyssagetaen": "ir_massagetaean_lang",
    "ir_agathyrsian": "ir_scythian_lang",
    "ir_cimmerian": "ir_scythian_lang",
    "ir_gelonian": "ir_scythian_lang",
    "ir_derbiccan": "ir_massagetaean_lang",
    "ir_jurcan": "ir_scythian_lang",
    "ir_kharesmian": "ir_sogdian_lang",
    "ir_phryni": "ir_bactrian_lang",
    "ir_tocharian": "ir_tocharian_lang",
    "ir_yuezhi": "ir_yuezhi_lang",
    "ir_wusun": "ir_wusun_lang",
    # Germanic splits
    "ir_suebian": "ir_suebian_lang",
    "ir_saxonian": "ir_saxon_lang",
    "ir_anglian": "ir_saxon_lang",
    "ir_teutonian": "ir_saxon_lang",
    "ir_cimbrian": "ir_north_germanic_lang",
    "ir_suiones": "ir_north_germanic_lang",
    "ir_scandian": "ir_north_germanic_lang",
    "ir_raumarician": "ir_north_germanic_lang",
    "ir_reudingian": "ir_north_germanic_lang",
    "ir_gothonic": "ir_gothic_lang",
    "ir_gutones": "ir_gothic_lang",
    "ir_vandal": "ir_gothic_lang",
    "ir_herulian": "ir_gothic_lang",
    "ir_rugian": "ir_gothic_lang",
    "ir_lemovian": "ir_gothic_lang",
    "ir_frisian": "ir_saxon_lang",
    "ir_irminonic": "ir_suebian_lang",
    "ir_istvaeonic": "ir_suebian_lang",
    "ir_ingvaeonic": "ir_saxon_lang",
    "ir_helveconian": "ir_suebian_lang",
    "ir_bastarnae": "ir_suebian_lang",
    "ir_indo_germanic": "ir_suebian_lang",
    # Baltic splits
    "ir_aestian": "ir_aestian_lang",
    "ir_neuric": "ir_neuric_lang",
    "ir_sporic": "ir_neuric_lang",
    "ir_budinian": "ir_neuric_lang",
    "ir_chernolian": "ir_neuric_lang",
    "ir_melanchlaenian": "ir_neuric_lang",
    # Finnic splits
    "ir_mordvin": "ir_mordvin_lang",
    "ir_volgaic": "ir_volgaic_lang",
    "ir_androphagian": "ir_volgaic_lang",
    "ir_fennic": "ir_proto_finnic_lang",
    # Celto-Pannonian splits
    "ir_galatian": "ir_celtiberian_lang",
    "ir_tylian": "ir_celtiberian_lang",
    # Gaels
    "ir_hibernian": "ir_goidelic_lang",
    "ir_manavian": "ir_goidelic_lang",
    # African splits
    "ir_blemmyan": "ir_blemmye_lang",
    "ir_blemmye": "ir_blemmye_lang",
    "ir_puntic": "ir_puntic_lang",
    "ir_avalitian": "ir_puntic_lang",
    "ir_erythraean": "ir_puntic_lang",
    "ir_berberian": "ir_gaetulian_lang",
    "ir_abannaean": "ir_mauritanian_lang",
    "ir_perorsian": "ir_mauritanian_lang",
    "ir_pharusian": "ir_mauritanian_lang",
    "ir_lixitoi": "ir_mauritanian_lang",
    # Meroitic/Nilotic splits
    "ir_lower_nubian": "ir_nubian_lang",
    "ir_napatan": "ir_meroitic_lang",
    "ir_meroitic": "ir_meroitic_lang",
    "ir_nubian": "ir_nubian_lang",
    "ir_adabulian": "ir_dinka_lang",
    "ir_alutan": "ir_dinka_lang",
    "ir_boran": "ir_dinka_lang",
    "ir_kumuzan": "ir_dinka_lang",
    "ir_midobian": "ir_dinka_lang",
    "ir_moyan": "ir_dinka_lang",
    "ir_rhizophagian": "ir_dinka_lang",
    "ir_zankorian": "ir_dinka_lang",
    # South Arabian
    "ir_adite": "ir_old_south_arabian_lang",
    "ir_hadhrami": "ir_old_south_arabian_lang",
    "ir_kindite": "ir_old_south_arabian_lang",
    "ir_minaean": "ir_old_south_arabian_lang",
    "ir_qatabanian": "ir_old_south_arabian_lang",
    "ir_samad": "ir_old_south_arabian_lang",
    "ir_sheban": "ir_old_south_arabian_lang",
    # West Levantine
    "ir_phoenician": "ir_phoenician_lang",
    # Chinese
    "ir_qin": "ir_old_chinese_lang",
    # Tibetan
    "ir_pyu": "ir_tibetic_lang",
    "ir_sumpa": "ir_tibetic_lang",
    "ir_tsang": "ir_tibetic_lang",
    "ir_yarlung": "ir_tibetic_lang",
    "ir_zhangzhung": "ir_tibetic_lang",
    # PU
    "ir_jaintia": "ir_punic_lang",
    "ir_mon": "ir_punic_lang",
    "ir_pubu": "ir_punic_lang",
    "ir_rhakine": "ir_punic_lang",
    "ir_shan": "ir_punic_lang",
    # Aksumite leftovers
    "ir_aksumite": "ir_geez_lang",
    "ir_athagaun": "ir_geez_lang",
    "ir_daamoti": "ir_geez_lang",
    "ir_ona": "ir_geez_lang",
    "ir_kannadan": "ir_kannada_lang",
    "ir_telugu": "ir_telugu_lang",
    "ir_sindhi": "ir_sindhi_lang",
    "ir_kalingan": "ir_oriya_lang",
    "ir_kamarupi": "ir_kamarupi_lang",
    "ir_bangli": "ir_bengali_lang",
    "ir_himalayan": "ir_himalayan_lang",
    # India splits
    "ir_gandhari": "ir_gandhari_lang",
    "ir_dardic": "ir_gandhari_lang",
    "ir_tamil": "ir_tamil_lang",
    "ir_cheran": "ir_tamil_lang",
    "ir_cholan": "ir_tamil_lang",
    "ir_pandyan": "ir_tamil_lang",
    "ir_andhran": "ir_telugu_lang",
    "ir_alupan": "ir_kannada_lang",
    "ir_kuntalan": "ir_kannada_lang",
    "ir_assaka": "ir_prakrit_lang",
    # Aryan/Indo-Aryan splits
    "ir_kaccha": "ir_sindhi_lang",
    "ir_saurashtran": "ir_sindhi_lang",
    "ir_rathikan": "ir_sindhi_lang",
    "ir_dhivehi": "ir_sindhi_lang",
    "ir_lankan": "ir_prakrit_lang",
    "ir_maharashtran": "ir_prakrit_lang",
    "ir_mulaka": "ir_prakrit_lang",
    "ir_vidharban": "ir_prakrit_lang",
    "ir_shauraseni": "ir_prakrit_lang",
    "ir_avanti": "ir_sanskrit_lang",
    "ir_cedi": "ir_sanskrit_lang",
    "ir_kosala": "ir_sanskrit_lang",
    "ir_kuru": "ir_sanskrit_lang",
    "ir_matsya": "ir_sanskrit_lang",
    "ir_purus": "ir_sanskrit_lang",
    "ir_sivi": "ir_sanskrit_lang",
    "ir_mitanni": "ir_sanskrit_lang",
    # Pracyan splits (Eastern India)
    "ir_magadhi": "ir_magadhan_prakrit_lang",
    "ir_kasi": "ir_magadhan_prakrit_lang",
    "ir_malla": "ir_magadhan_prakrit_lang",
    "ir_vrji": "ir_magadhan_prakrit_lang",
    "ir_vanga": "ir_bengali_lang",
    "ir_pandra": "ir_bengali_lang",
    "ir_atavi": "ir_oriya_lang",
    "ir_savara": "ir_oriya_lang",
}

# Per-culture overrides when a specific culture should use a more precise gfx tag.
ir_culture_graphical_overrides = {
    "ir_armenian": ["caucasian_gfx", "middle_east_gfx", "european_gfx"],
    "ir_hebrew": ["israelite_gfx", "levantine_gfx", "middle_east_gfx"],
}

# Manual overrides for generated EU5 formable requirements.
# Use this when a generated scope is technically valid but design-wise not desired.
# Supported keys per tag:
# - "areas": list[str]
# - "regions": list[str]
# - "locations": list[str]  # location keys (not province IDs)
# - "required_locations_fraction": float
#
# Scope precedence in writer:
#   locations > areas > regions
#
# Tags listed here are intentionally excluded from generated EU5 formables.
# Use this for ahistorical/joke artifacts from upstream decision pools.
disabled_formable_tags: set[str] = {
    "IGK",  # Indo-Germanic Kingdom (nonsense alt-formable)
    # Exact-scope duplicates: keep one canonical representative.
    "AGO",  # Duplicate scope with ARK.
    "CHY",  # Duplicate scope with CIA.
    "DL2",  # Duplicate scope with PH2 (Delphic flavor preserved on PH2).
    "KHN",  # Duplicate scope with YZI.
    "POG",  # Duplicate scope with PRU.
}

# Duplicate/synonym formables should resolve to a single canonical output tag.
# This keeps one formable entry while allowing flavor wording through
# country_ranks/country_name_construction.
formable_alias_target_overrides: dict[str, str] = {
    "ACL": "ACH",  # Achaean League -> Achaea (League flavor via rank/construction)
}


# Curated custom regional formables (outside vanilla I:R / Invictus pools).
# These are injected in extract_data and emitted like regular generated formables.
custom_formable_data: dict[str, dict[str, object]] = {
    "ANA": {
        "level": 3,
        "name": "Anatolia",
        "adj": "Anatolian",
        "required_locations_fraction": 0.6,
        "scope": {"regions": ["anatolia_region"]},
        "potential_lines": [
            "OR = {",
            "    culture = { has_culture_group = culture_group:ir_anatolian_g }",
            "    culture = { has_culture_group = culture_group:ir_hellenic_g }",
            "}",
        ],
    },
    "CAU": {
        "level": 3,
        "name": "Caucasia",
        "adj": "Caucasian",
        "required_locations_fraction": 0.6,
        "scope": {"regions": ["caucasus_region"]},
        "potential_lines": [
            "OR = {",
            "    culture = { has_culture_group = culture_group:ir_caucasian_g }",
            "    culture = culture:ir_armenian",
            "}",
        ],
    },
    "KAB": {
        "level": 3,
        "name": "Maghreb",
        "adj": "Maghrebi",
        "required_locations_fraction": 0.6,
        "scope": {"regions": ["maghreb_region"]},
        "potential_lines": [
            "OR = {",
            "    culture = { has_culture_group = culture_group:ir_numidian_g }",
            "    culture = { has_culture_group = culture_group:ir_north_african_g }",
            "}",
        ],
    },
    "HRP": {
        "level": 3,
        "name": "Carpathia",
        "adj": "Carpathian",
        "required_locations_fraction": 0.6,
        "scope": {"regions": ["carpathia_region"]},
        "potential_lines": [
            "OR = {",
            "    culture = { has_culture_group = culture_group:ir_dacia_group_g }",
            "    culture = { has_culture_group = culture_group:ir_thrace_group_g }",
            "}",
        ],
    },
    "GTE": {
        "level": 3,
        "name": "Balkans",
        "adj": "Balkan",
        "required_locations_fraction": 0.6,
        "scope": {"regions": ["balkan_region"]},
        "potential_lines": [
            "OR = {",
            "    culture = { has_culture_group = culture_group:ir_illyrian_group_g }",
            "    culture = { has_culture_group = culture_group:ir_thrace_group_g }",
            "    culture = { has_culture_group = culture_group:ir_hellenic_g }",
            "}",
        ],
    },
    "GTH": {
        "level": 3,
        "name": "Baltica",
        "adj": "Baltic",
        "required_locations_fraction": 0.6,
        "scope": {"regions": ["baltic_region"]},
        "potential_lines": [
            "OR = {",
            "    culture = { has_culture_group = culture_group:ir_baltic_g }",
            "    culture = { has_culture_group = culture_group:ir_finnic_group_g }",
            "}",
        ],
    },
    "KRZ": {
        "level": 3,
        "name": "Khorasan",
        "adj": "Khorasani",
        "required_locations_fraction": 0.6,
        "scope": {"regions": ["khorasan_region"]},
        "potential_lines": [
            "OR = {",
            "    culture = { has_culture_group = culture_group:ir_persia_g }",
            "    culture = { has_culture_group = culture_group:ir_scythia_g }",
            "}",
        ],
    },
    "KSH": {
        "level": 3,
        "name": "Nile Realm",
        "adj": "Nile",
        "required_locations_fraction": 0.6,
        "scope": {"regions": ["egypt_region", "nubia_region"]},
        "potential_lines": [
            "OR = {",
            "    culture = { has_culture_group = culture_group:ir_meroitic_group_g }",
            "    culture = { has_culture_group = culture_group:ir_north_african_g }",
            "    culture = { has_culture_group = culture_group:ir_nilotic_group_g }",
            "}",
        ],
    },
}

formable_requirement_overrides: dict[str, dict[str, object]] = {
    # Endgame / large unions
    "APF": {
        "regions": ["cisalpine_gaul_region", "transalpine_gaul_region", "rhaetia_region"],
        "required_locations_fraction": 0.6,
        "required_culture_groups": ["latin", "gallic", "celto_pannonian_group"],
    },
    "PLL": {
        "regions": ["greece_region", "macedonia_region"],
        "required_locations_fraction": 0.6,
        "required_culture_groups": ["hellenic"],
    },
    "VC1": {
        "regions": ["italy_region", "illyria_region", "greece_region"],
        "required_locations_fraction": 0.6,
        "required_culture_groups": ["latin"],
    },
    "VC2": {
        "regions": ["cisalpine_gaul_region", "illyria_region"],
        "required_locations_fraction": 0.6,
        "required_culture_groups": ["latin"],
    },

    # Mid-tier formables
    "ARI": {
        "regions": ["armenia_region", "cappadocia_region"],
        "required_locations_fraction": 0.75,
        "required_culture_groups": ["anatolian"],
    },
    "BPL": {
        "regions": ["taurica_region", "pontus_region"],
        "required_locations_fraction": 0.7,
        "required_culture_groups": ["hellenic", "scythia"],
    },
    "DRA": {
        "areas": ["drangiana_area"],
        "required_locations_fraction": 0.75,
        "required_culture_groups": ["persia"],
    },
    "ENG": {
        "regions": ["great_britain_region"],
        "required_locations_fraction": 0.7,
        "required_culture_groups": ["germanic", "britannic"],
    },
    "FEZ": {
        "regions": ["fezzan_region"],
        "required_locations_fraction": 0.75,
        "required_primary_cultures": ["macaean", "psyllic", "nasamonian", "garamantic", "phazani"],
    },
    "FRA": {
        "regions": ["france_region"],
        "required_locations_fraction": 0.7,
        "required_culture_groups": ["germanic", "gallic"],
    },
    "ISL": {
        "areas": ["histria_area", "venetia_area", "dalmatia_centralis_area"],
        "required_locations_fraction": 0.75,
        "required_culture_groups": ["illyrian_group", "latin"],
    },
    "PTL": {
        "regions": ["cappadocia_pontica_region", "pontus_region"],
        "required_locations_fraction": 0.75,
        "required_culture_groups": ["hellenic", "anatolian"],
    },
    "SAR": {
        "areas": ["sardinia_meridionalis", "sardinia_septentrionalis"],
        "required_locations_fraction": 0.8,
    },
    "TAT": {
        "areas": [
            "baetica_cordubensis_area",
            "baetica_hispalensis_area",
            "turdetania_occidentalis_area",
            "bastetania_area",
        ],
        "required_locations_fraction": 0.75,
        "required_culture_groups": ["iberia", "celt_iberia"],
    },
    "YZI": {
        # IR uses OR over a small set of locations; approximate with low area fraction.
        "areas": ["ferghana_area", "tarim_area", "talas_area", "cyropolis_area"],
        "required_locations_fraction": 0.3,
    },

    # Tier-1 fallback
    "KMR": {
        "areas": ["gandhara_area"],
        "required_locations_fraction": 0.75,
        "required_culture_groups": ["aryan", "persia"],
    },
    "AVK": {
        "required_culture_groups": ["gallic", "latin"],
    },
    "CCI": {
        "required_culture_groups": ["anatolian", "hellenic"],
    },
    "KRE": {
        "required_culture_groups": ["hellenic"],
    },
    "LO2": {
        "required_culture_groups": ["hellenic"],
    },
    "PEN": {
        "required_culture_groups": ["indian", "persia"],
    },
    "PH2": {
        "required_culture_groups": ["hellenic"],
    },
    "PRU": {
        "required_culture_groups": ["indian"],
    },
}

# Explicit localisation overrides for generated formables.
# Use these to keep short EU5-style display names while rank/government wording
# is handled by country name construction rules.
formable_localization_overrides: dict[str, dict[str, str]] = {
    "ACL": {"name": "Achaea", "adj": "Achaean"},
    "ALX": {"name": "Argeads", "adj": "Argead"},
    "APF": {"name": "Alps", "adj": "Alpine"},
    "ARI": {"name": "Ariarathids", "adj": "Ariarathid"},
    "AVK": {"name": "Arvernia", "adj": "Arvernian"},
    "BPL": {"name": "Bosporus", "adj": "Bosporan"},
    "CCC": {"name": "Caledonia", "adj": "Caledonian"},
    "DLA": {"name": "Delos", "adj": "Delian"},
    "EGY": {"name": "Ptolemies", "adj": "Ptolemaic"},
    "HLA": {"name": "Hellas", "adj": "Hellenic"},
    "IOU": {"name": "Ionia", "adj": "Ionian"},
    "ISK": {"name": "Indo-Scythia", "adj": "Indo-Scythian"},
    "ISL": {"name": "Istria", "adj": "Istrian"},
    "NMT": {"name": "Mitanni", "adj": "Mitanni"},
    "OYK": {"name": "Odrysia", "adj": "Odrysian"},
    "PLL": {"name": "Peloponnese", "adj": "Peloponnesian"},
    "PRY": {"name": "Antigonids", "adj": "Antigonid"},
    "PTL": {"name": "Pontus", "adj": "Pontic"},
    "PH2": {"name": "Phocis", "adj": "Phocian"},
    "SEL": {"name": "Seleukids", "adj": "Seleukid"},
    "SL1": {"name": "Salluvia", "adj": "Salluvian"},
    "VC1": {"name": "Venice", "adj": "Venetian"},
    "VC2": {"name": "Veneti", "adj": "Venetic"},
}

# ---------------- Map Conversion Static Mappings ---------------- #

continent_map = {
    "europe": [
        "western_europe",
        "eastern_europe",
    ],
    "asia": [
        "middle_east",
        "south_asia",
        "central_asia",
    ],
    "africa": [
        "north_africa",
        "east_africa",
    ],
}

superregion_map = {
    "western_europe": {
        "italy_region": [
            "central_italy_region",
            "magna_graecia_region",
            "cisalpine_gaul_region",
            "mediterranean_region",
        ],
        "north_german_region": [
            "belgica_region",
            "germania_region",
        ],
        "south_german_region": [
            "germania_superior_region",
            "rhaetia_region",
            "bohemia_area",
        ],
        "france_region": [
            "transalpine_gaul_region",
            "central_gaul_region",
            "armorica_region",
            "aquitaine_region",
        ],
        "iberia_region": [
            "lusitania_region",
            "tarraconensis_region",
            "baetica_region",
            "contestania_region",
            "gallaecia_region",
            "western_mediterranean_river_region",
        ],
        "great_britain_region": [
            "britain_region",
            "caledonia_region",
        ],
        "scandinavian_region": [
            "scandinavia_region",
            "baltic_sea_region",
            "north_sea_river_region",
        ],
        "north_atlantic_islands_region": [
            "atlantic_region",
            "northern_atlantic_river_region",
            "southern_atlantic_river_region",
        ],
    },
    "eastern_europe": {
        "balkan_region": [
            "greece_region",
            "macedonia_region",
            "illyria_region",
            "thrace_region",
            "moesia_region",
            "moesia_s_region",
        ],
        "carpathia_region": [
            "dacia_region",
            "pannonia_region",
        ],
        "baltic_region": [
            "vistulia_region",
            "venedia_region",
            "hyperborea_region",
            "baltic_river_region",
        ],
        "steppes_region": [
            "sarmatia_europea_region",
            "borysthenia_region",
            "black_sea_river_region",
            "taurica_region",
            "scythia_region",
            "don_river_region",
        ],
        "caucasus_region": [
            "armenia_region",
            "colchis_region",
            "albania_region",
        ],
    },
    "middle_east": {
        "anatolia_region": [
            "asia_region",
            "bithynia_region",
            "galatia_region",
            "cappadocia_region",
            "cappadocia_pontica_region",
            "cilicia_region",
            "pontus_region",
            "cilician_river_region",
        ],
        "persia_region": [
            "gedrosia_region",
            "persis_region",
            "media_region",
            "bactriana_region",
            "ariana_region",
        ],
        "arabia_region": [
            "arabia_region",
            "arabia_felix_region",
            "persian_gulf_region",
            "red_sea_region",
        ],
        "crescent_region": [
            "assyria_region",
            "mesopotamia_region",
            "mesopotamia_river_region",
            "syria_region",
            "palestine_region",
            "eastern_mediterranean_river_region",
        ],
    },
    "south_asia": {
        "hindustan_region": [
            "gandhara_region",
            "maru_region",
            "avanti_region",
            "madhyadesa_region",
            "indo_gangetic_region",
        ],
        "deccan_region": [
            "vindhyaprstha_region",
            "dravida_region",
            "aparanta_region",
            "karnata_region",
            "southern_india_river_region",
            "western_india_river_region",
        ],
        "bengal_region": [
            "pracya_region",
            "indian_ocean_region",
            "burma_region",
        ],
    },
    "central_asia": {
        "tibet_region": [
            "tibet_region",
        ],
        "khorasan_region": [
            "himalayan_region",
            "sogdiana_region",
            "central_asian_steppes_region",
            "sarmatia_asiatica_region",
            "sakia_region",
            "parthia_region",
        ],
    },
    "north_africa": {
        "maghreb_region": [
            "numidia_region",
            "mauretainia_region",
            "africa_region",
            "atlas_region",
        ],
        "egypt_region": [
            "cyrenaica_region",
            "fezzan_region",
            "upper_egypt_region",
            "lower_egypt_region",
            "nile_region",
        ],
    },
    "east_africa": {
        "nubia_region": [
            "nubia_region",
            "lower_nubia_region",
        ],
        "ethiopia_region": [
            "punt_region",
        ],
    },
}

IR_GROUP_TOWN_SETUPS = {
    "ir_hellenic_g": {
        "city": "greek_city_port",
        "city_port": "greek_city_port",
        "town": "greek_town",
        "town_port": "greek_town_port",
    },
    "ir_latin_g": {
        "city": "italian_city",
        "city_port": "italian_coastal_city",
        "town": "italian_town",
        "town_port": "italian_coastal_town",
    },
    "ir_iberia_g": {
        "city": "iberian_city",
        "city_port": "iberian_city_port",
        "town": "iberian_town",
        "town_port": "iberian_town_port",
    },
    "ir_celt_iberia_g": {
        "city": "iberian_city",
        "city_port": "iberian_city_port",
        "town": "iberian_town",
        "town_port": "iberian_town_port",
    },
    "ir_germanic_g": {
        "city": "german_city",
        "city_port": "german_coastal_city",
        "town": "german_town",
        "town_port": "german_coastal_town",
    },
    "ir_britannic_g": {
        "city": "british_town",
        "city_port": "british_town_port",
        "town": "british_town",
        "town_port": "british_town_port",
    },
    "ir_gaelic_g": {
        "city": "british_town",
        "city_port": "british_town_port",
        "town": "british_town",
        "town_port": "british_town_port",
    },
    "ir_gallic_g": {"city": "french_city", "town": "french_town"},
    "ir_belgae_group_g": {
        "city": "lowlands_city",
        "city_port": "lowlands_coastal_city",
        "town": "lowlands_town",
        "town_port": "lowlands_costal_town",
    },
    "ir_celto_pannonian_group_g": {
        "city": "carpathian_town",
        "town": "carpathian_town",
    },
    "ir_dacia_group_g": {"city": "carpathian_town", "town": "carpathian_town"},
    "ir_illyrian_group_g": {"city": "balkan_town", "town": "balkan_town"},
    "ir_baltic_g": {"city": "baltic_town", "town": "baltic_town"},
    "ir_scythia_g": {
        "city": "central_asian_city",
        "town": "central_asian_town",
    },
    "ir_persia_g": {
        "city": "central_asian_city",
        "town": "central_asian_town",
    },
    "ir_bactrian_g": {
        "city": "central_asian_city",
        "town": "central_asian_town",
    },
    "ir_aryan_g": {
        "city": "indian_city",
        "city_port": "indian_coastal_city",
        "town": "indian_town",
    },
    "ir_pracyan_g": {
        "city": "indian_city",
        "city_port": "indian_coastal_city",
        "town": "indian_town",
    },
    "ir_indian_g": {
        "city": "indian_city",
        "city_port": "indian_coastal_city",
        "town": "indian_town",
    },
    "ir_tibetan_g": {
        "city": "central_asian_city",
        "town": "central_asian_town",
    },
    "ir_anatolian_g": {
        "city": "anatolian_city",
        "town": "anatolian_town",
    },
    "ir_caucasian_g": {
        "city": "central_asian_city",
        "town": "central_asian_town",
    },
    "ir_east_levantine_g": {
        "city": "levant_city",
        "town": "levant_town",
    },
    "ir_west_levantine_g": {
        "city": "levant_city",
        "town": "levant_town",
    },
    "ir_south_levantine_g": {
        "city": "levant_city",
        "town": "levant_town",
    },
    "ir_north_african_g": {
        "city": "egyptian_city",
        "city_port": "maghreb_coastal_city",
        "town": "maghreb_town",
        "town_port": "maghreb_coastal_town",
    },
    "ir_numidian_g": {
        "city": "maghreb_city",
        "city_port": "maghreb_coastal_city",
        "town": "maghreb_town",
        "town_port": "maghreb_coastal_town",
    },
    "ir_meroitic_group_g": {
        "city": "east_african_town",
        "city_port": "east_african_coastal_town",
        "town": "east_african_town",
        "town_port": "east_african_coastal_town",
    },
    "ir_aksumite_group_g": {
        "city": "east_african_town",
        "city_port": "east_african_coastal_town",
        "town": "east_african_town",
        "town_port": "east_african_coastal_town",
    },
    "ir_proto_european_g": {"city": "french_city", "town": "french_town"},
}

IR_BUILDING_MAP_OVERRIDES = {
    # Map I:R buildings to EU5 base buildings to preserve base functionality.
    "fortress_building": "castle",
    "fortress_ramparts_building": "bastion",
    "hill_fort": "stockade",
    "port_building": "dock",
    "barracks_building": "barracks",
    "military_building": "armory",
    "foundry_building": "mason",
    "workshop_building": "tools_workshop",
    "commerce_building": "marketplace",
    "forum_building": "merchants_quarters",
    "court_building": "counting_house",
    "town_hall_building": "minting_office",
    "temple_building": "temple",
    "library_building": "library",
    "academy_building": "university",
    "theathre_building": "theater",
    "aqueduct_building": "construction_center",
    "population_building": "granary",
    "latifundia_building": "farming_village",
    "basic_settlement_infratructure_building": "market_village",
    "slave_mine_building": "slave_market",
    "local_forum_building": "bailiff",
}

IR_GOODS_TO_EU5_GOODS = {
    "grain": ("wheat", "rice", "maize"),
    "vegetables": ("wheat", "rice", "maize"),
    "wood": ("lumber",),
    "base_metals": ("iron", "copper", "lead", "tin"),
    "precious_metals": ("goods_gold", "silver"),
    "marble": ("stone",),
    "olive": ("wine", "wheat"),
    "papyrus": ("paper", "fiber_crops", "cloth"),
    "elephants": ("ivory",),
    "gemstones": ("gems",),
    "spices": ("incense", "tea"),
    "silk": ("silk",),
    "incense": ("incense",),
    "fish": ("fish",),
    "salt": ("salt",),
    "horses": ("horses",),
    "steppe_horses": ("horses",),
    "wine": ("wine",),
    "amber": ("amber",),
    "stone": ("stone",),
    "glass": ("glass",),
    "cloth": ("cloth", "fiber_crops"),
    "dye": ("dyes",),
    "fur": ("fur",),
    "wild_game": ("wild_game",),
    "cattle": ("wool",),
    "leather": ("fur", "wool"),
    "hemp": ("fiber_crops",),
    "woad": ("dyes",),
    "honey": ("wheat",),
    "dates": ("wheat",),
    "earthware": ("clay",),
    "camel": ("horses",),
}

IR_GOODS_WEIGHT_OVERRIDES = {
    "grain": {
        "wheat": 1.0,
        "rice": 0.6,
        "maize": 0.15,
    },
    "vegetables": {
        "wheat": 1.0,
        "rice": 0.6,
        "maize": 0.15,
    },
    "base_metals": {
        "iron": 1.0,
        "copper": 0.7,
        "lead": 0.4,
        "tin": 0.2,
    },
    "precious_metals": {
        "goods_gold": 0.25,
        "silver": 1.0,
    },
    "olive": {
        "wine": 0.8,
        "wheat": 0.3,
    },
    "papyrus": {
        "paper": 0.3,
        "fiber_crops": 1.0,
        "cloth": 0.6,
    },
    "spices": {
        "incense": 1.0,
        "tea": 0.2,
    },
    "cloth": {
        "cloth": 1.0,
        "fiber_crops": 0.5,
    },
    "leather": {
        "fur": 0.4,
        "wool": 1.0,
    },
}

PORT_SEAZONE_OVERRIDES = {
    "calacte": "mare_tyrrenum",
}

IR_TERRAIN_TO_TOPOGRAPHY = {
    "plains": "flatland",
    "farmland": "flatland",
    "forest": "flatland",
    "jungle": "flatland",
    "desert": "flatland",
    "hills": "hills",
    "mountain": "mountains",
    "marsh": "wetlands",
    "coastal_terrain": "flatland",
    "riverine_terrain": "flatland",
    "impassable_terrain": "mountains",
}

IR_TERRAIN_TO_VEGETATION = {
    "plains": "grasslands",
    "farmland": "farmland",
    "forest": "forest",
    "jungle": "jungle",
    "desert": "desert",
    "hills": "woods",
    "mountain": "sparse",
    "marsh": "woods",
    "coastal_terrain": "grasslands",
    "riverine_terrain": "grasslands",
    "impassable_terrain": "sparse",
}

IR_CLIMATE_TO_EU5_CLIMATE = {
    "mild_winter": "oceanic",
    "normal_winter": "continental",
    "severe_winter": "arctic",
    "arid": "arid",
}

MEDITERRANEAN_COASTAL_AREAS_RAW = {
    "central_italy_region",
    "magna_graecia_region",
    "cisalpine_gaul_region",
    "transalpine_gaul_region",
    "central_gaul_region",
    "armorica_region",
    "aquitaine_region",
    "lusitania_region",
    "tarraconensis_region",
    "baetica_region",
    "contestania_region",
    "gallaecia_region",
    "greece_region",
    "macedonia_region",
    "illyria_region",
    "thrace_region",
    "moesia_region",
    "moesia_s_region",
    "taurica_region",
    "asia_region",
    "bithynia_region",
    "galatia_region",
    "cappadocia_pontica_region",
    "cilicia_region",
    "pontus_region",
    "armenia_region",
    "colchis_region",
    "albania_region",
    "arabia_region",
    "arabia_felix_region",
    "assyria_region",
    "mesopotamia_region",
    "syria_region",
    "palestine_region",
    "numidia_region",
    "mauretainia_region",
    "africa_region",
    "cyrenaica_region",
    "upper_egypt_region",
    "lower_egypt_region",
}

MEDITERRANEAN_COASTAL_AREAS = {
    "central_italy_area",
    "magna_graecia_area",
    "cisalpine_gaul_area",
    "transalpine_gaul_area",
    "central_gaul_area",
    "armorica_area",
    "aquitaine_area",
    "lusitania_area",
    "tarraconensis_area",
    "baetica_area",
    "contestania_area",
    "gallaecia_area",
    "greece_area",
    "macedonia_area",
    "illyria_area",
    "thrace_area",
    "moesia_area",
    "moesia_s_area",
    "taurica_area",
    "asia_area",
    "bithynia_area",
    "galatia_area",
    "cappadocia_pontica_area",
    "cilicia_area",
    "pontus_area",
    "armenia_area",
    "colchis_area",
    "albania_area",
    "arabia_area",
    "arabia_felix_area",
    "assyria_area",
    "mesopotamia_area",
    "syria_area",
    "palestine_area",
    "numidia_area",
    "mauretainia_area",
    "africa_area",
    "cyrenaica_area",
    "upper_egypt_area",
    "lower_egypt_area",
}
