from __future__ import annotations

import os
from pathlib import Path
from typing import List, Tuple, Union

import pyradox.datatype as _pydt
import pyradox.token as _pytoken

from .paths import mod_root



AUTO_GENERATED_HEADER = (
    "# =========================================================== #\n"
    "#            THIS FILE IS AUTOMATICALLY GENERATED!            #\n"
    "#  Any manual changes will be OVERWRITTEN upon regeneration!  #\n"
    "# =========================================================== #\n\n"
)

def print_written(kind: str, out_path: Path) -> None:
    """Print a concise relative write message for `out_path`."""
    try:
        rel = os.path.relpath(str(out_path), start=str(mod_root))
    except Exception:
        rel = str(out_path)
    print(f"Writing {kind}: {rel}")


def convert_color(color: _pydt.Color) -> str:
    if color.colorspace == "rgb":
        r, g, b = color.channels
        return f"rgb {{ {r} {g} {b} }}"
    if color.colorspace == "hsv":
        h, s, v = color.channels
        return f"hsv {{ {h:.2f} {s:.2f} {v:.2f} }}"
    raise ValueError(f"Unsupported color space: {color.colorspace}")


def convert_tree_to_blocks(
    tree: _pydt.Tree,
) -> List[Union[str, Tuple[str, List[object]]]]:
    blocks: List[Union[str, Tuple[str, List[object]]]] = []
    grouped: dict[str, list] = {}

    for key, value in tree.items():
        grouped.setdefault(key, []).append(value)

    for key, values in grouped.items():
        if all(not isinstance(v, (_pydt.Tree, list)) for v in values):
            formatted_values = [_pytoken.make_token_string(v) for v in values]
            if len(formatted_values) == 1:
                blocks.append(f"{key} = {formatted_values[0]}")
            else:
                blocks.append(f"{key} = {{ {' '.join(formatted_values)} }}")
            continue

        if all(isinstance(v, list) for v in values):
            flat: list[object] = []
            has_complex = False
            for v in values:
                for item in v:
                    if isinstance(item, (_pydt.Tree, list)):
                        has_complex = True
                        break
                    flat.append(item)
                if has_complex:
                    break
            if not has_complex:
                formatted = " ".join(_pytoken.make_token_string(item) for item in flat)
                blocks.append(f"{key} = {{ {formatted} }}")
                continue

        for v in values:
            if isinstance(v, _pydt.Tree):
                blocks.append((key, convert_tree_to_blocks(v)))
            elif isinstance(v, list):
                for item in v:
                    if isinstance(item, _pydt.Tree):
                        blocks.append((key, convert_tree_to_blocks(item)))
                    else:
                        blocks.append(f"{key} = {_pytoken.make_token_string(item)}")

    return blocks


def make_block(
    tag: str,
    lines: List[Union[str, Tuple[str, List[object]]]] | None = None,
    indent_level: int = 0,
    indent_str: str = "    ",
) -> str:
    if lines is None:
        lines = []

    prefix = indent_str * indent_level
    inner_prefix = prefix + indent_str

    parts: List[str] = [f"{prefix}{tag} = {{\n"]
    for line in lines:
        if isinstance(line, tuple) and len(line) == 2:
            subtag, sublines = line
            parts.append(make_block(subtag, sublines, indent_level + 1, indent_str))
        else:
            parts.append(f"{inner_prefix}{line}\n")
    parts.append(f"{prefix}}}\n")
    return "".join(parts)


def write_blocks(
    out_path: Path,
    blocks: Union[
        str,
        Tuple[str, List[object]],
        List[Union[str, Tuple[str, List[object]]]],
    ],
    mode: str = "w",
    encoding: str = "utf-8-sig",
    indent_str: str = "    ",
    header: str = AUTO_GENERATED_HEADER,
) -> Path:
    if isinstance(blocks, (tuple, str)):
        blocks_list = [blocks]
    elif isinstance(blocks, list):
        blocks_list = blocks
    elif isinstance(blocks, _pydt.Tree):
        blocks_list = convert_tree_to_blocks(blocks)
    else:
        raise TypeError("blocks must be a str, a (tag, lines) tuple, or a list")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open(mode, encoding=encoding) as handle:
        if header:
            handle.write(header)
        for block in blocks_list:
            if isinstance(block, tuple) and len(block) == 2:
                tag, lines = block
                content = make_block(tag, lines, indent_level=0, indent_str=indent_str)
                handle.write(content.replace("{ {} }", "{}"))
                handle.write("\n")
            else:
                s = str(block).replace("{ {} }", "{}")
                handle.write(s)
                if not s.endswith("\n"):
                    handle.write("\n")
                if out_path.suffix not in (".yml", ".yaml"):
                    handle.write("\n")

    print_written("file", out_path)
    return out_path
