import os
from collections import defaultdict
from pathlib import Path
from typing import List, Tuple, Union

import pyradox
import pyradox.datatype as _pydt

from .data import (
    government_map,
    ir_culture_group_language_map,
    ir_culture_language_overrides,
    ir_culture_group_graphical_map,
    ir_culture_graphical_overrides,
)
from .paths import *

pyradox.Color = _pydt.Color
pyradox.Tree = _pydt.Tree

AUTO_GENERATED_HEADER = (
    "# =========================================================== #\n"
    "#            THIS FILE IS AUTOMATICALLY GENERATED!            #\n"
    "#  Any manual changes will be OVERWRITTEN upon regeneration!  #\n"
    "# =========================================================== #\n\n"
)


def ensure_list(value):
    return value if isinstance(value, list) else [value]


def print_written(kind: str, out_path: Path) -> None:
    """Print a concise relative write message for `out_path`.

    `kind` should be a short label like 'file', 'JSON', 'CSV', or 'image'.
    """
    try:
        rel = os.path.relpath(str(out_path), start=str(mod_root))
    except Exception:
        rel = str(out_path)
    print(f"Writing {kind}: {rel}")


def convert_color(color: _pydt.Color) -> str:
    if color.colorspace == "rgb":
        r, g, b = color.channels
        return f"rgb {{ {r} {g} {b} }}"
    elif color.colorspace == "hsv":
        h, s, v = color.channels
        return f"hsv {{ {h:.2f} {s:.2f} {v:.2f} }}"
    else:
        raise ValueError(f"Unsupported color space: {color.colorspace}")


def convert_tree_to_blocks(
    tree: _pydt.Tree,
) -> List[Union[str, Tuple[str, List[object]]]]:
    blocks: List[Union[str, Tuple[str, List[object]]]] = []

    grouped: dict[str, list] = {}

    # Group repeated keys
    for key, value in tree.items():
        if key not in grouped:
            grouped[key] = []
        grouped[key].append(value)

    for key, values in grouped.items():
        # All scalar values → aggregate into one line
        if all(not isinstance(v, (_pydt.Tree, list)) for v in values):
            formatted_values = [
                f'"{v}"' if isinstance(v, str) else str(v) for v in values
            ]
            if len(formatted_values) == 1:
                blocks.append(f"{key} = {formatted_values[0]}")
            else:
                items = " ".join(formatted_values)
                blocks.append(f"{key} = {{ {items} }}")

        else:
            # Complex values: trees or lists
            for v in values:
                if isinstance(v, _pydt.Tree):
                    # Use the parent key as the tag, not the "tag" inside the tree
                    subblocks = convert_tree_to_blocks(v)
                    blocks.append((key, subblocks))
                elif isinstance(v, list):
                    for item in v:
                        if isinstance(item, _pydt.Tree):
                            # Again, parent key is used to avoid double nesting
                            subblocks = convert_tree_to_blocks(item)
                            blocks.append((key, subblocks))
                        else:
                            # Scalar inside a list
                            formatted = (
                                f'"{item}"' if isinstance(item, str) else str(item)
                            )
                            blocks.append(f"{key} = {formatted}")

    return blocks


def make_block(
    tag: str,
    lines: List[Union[str, Tuple[str, List[object]]]] | None = None,
    indent_level: int = 0,
    indent_str: str = "    ",
) -> str:
    if lines is None:
        lines = []

    prefix = indent_str * indent_level
    inner_prefix = prefix + indent_str

    parts: List[str] = [f"{prefix}{tag} = {{\n"]

    for line in lines:
        if isinstance(line, tuple) and len(line) == 2:
            subtag, sublines = line
            parts.append(make_block(subtag, sublines, indent_level + 1, indent_str))
        else:
            parts.append(f"{inner_prefix}{line}\n")

    parts.append(f"{prefix}}}\n")
    return "".join(parts)


def write_blocks(
    out_path: Path,
    blocks: Union[
        str,
        Tuple[str, List[object]],
        List[Union[str, Tuple[str, List[object]]]],
    ],
    mode: str = "w",
    encoding: str = "utf-8-sig",
    indent_str: str = "    ",
) -> Path:
    # normalize to a list of blocks
    if isinstance(blocks, (tuple, str)):
        blocks_list = [blocks]
    elif isinstance(blocks, list):
        blocks_list = blocks
    elif isinstance(blocks, _pydt.Tree):
        blocks_list = convert_tree_to_blocks(blocks)
    else:
        raise TypeError("blocks must be a str, a (tag, lines) tuple, or a list")

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open(mode, encoding=encoding) as f:
        # --- header ---
        f.write(AUTO_GENERATED_HEADER)

        for block in blocks_list:
            if isinstance(block, tuple) and len(block) == 2:
                tag, lines = block
                content = make_block(tag, lines, indent_level=0, indent_str=indent_str)
                # Collapse accidental double-empty-brace sequences (e.g. "{ {} }")
                content = content.replace("{ {} }", "{}")
                f.write(content)
                f.write("\n")
            else:
                s = str(block)
                s = s.replace("{ {} }", "{}")
                f.write(s)
                if not s.endswith("\n"):
                    f.write("\n")
                if out_path.suffix not in (".yml", ".yaml"):
                    f.write("\n")

    print_written("file", out_path)
    return out_path


def write_culture_group_data(culture_data: list):
    blocks = [(culture_group["tag"], []) for culture_group in culture_data]
    out_path = iu_culture_groups / f"ir_culture_groups.txt"
    write_blocks(out_path, blocks)


def write_culture_data(culture_data: list):
    for culture_group in culture_data:
        blocks = []

        def resolve_gfx_tags(value):
            tags = ensure_list(value) if value is not None else []
            resolved: list[str] = []
            for tag in tags:
                if isinstance(tag, str) and tag.startswith("ir_") and tag.endswith("_gfx"):
                    continue
                resolved.append(tag)

            seen = set()
            deduped = []
            for tag in resolved:
                if tag not in seen:
                    seen.add(tag)
                    deduped.append(tag)
            return deduped

        group_tag = culture_group.get("tag")
        group_gfx = None
        if group_tag:
            group_gfx = ir_culture_group_graphical_map.get(group_tag)
        if not group_gfx:
            group_gfx = culture_group["graphical_culture"]

        group_gfx = resolve_gfx_tags(group_gfx)

        for culture in culture_group["cultures"]:
            culture_tag = culture.get("tag")
            gfx_tag = (
                ir_culture_graphical_overrides.get(culture_tag)
                if culture_tag
                else None
            )
            if not gfx_tag:
                gfx_tag = group_gfx

            gfx_tags = resolve_gfx_tags(gfx_tag)
            gfx_tags_str = " ".join(gfx_tags)

            culture_language = None
            if culture_tag:
                culture_language = ir_culture_language_overrides.get(culture_tag)
            if not culture_language and group_tag:
                culture_language = ir_culture_group_language_map.get(group_tag)

            lines = [
                f"language = {culture_language}",
                f"color = {culture_group['color']}",
                f"tags = {{ {gfx_tags_str} }}",
                f"culture_groups = {{ {culture_group['tag']} }}",
            ]

            blocks.append((culture["tag"], lines))

        out_path = iu_cultures / f"{culture_group['tag']}.txt"

        write_blocks(out_path, blocks)


def write_religion_group_data(religion_data: list):
    blocks = [
        (
            "ir_religion_group",
            [
                "# Will probably need to change this manually later",
                f"color = rgb {{ 255 255 255 }}",
            ],
        )
    ]

    out_path = iu_religion_groups / f"ir_default.txt"

    write_blocks(out_path, blocks)


def write_religion_data(religion_data: list):
    blocks = [
        (
            religion["tag"],
            [
                f"color = {convert_color(religion['color'])}",
                f"group = ir_religion_group",
            ],
        )
        for religion in religion_data
    ]

    out_path = iu_religions / f"ir_religions.txt"

    write_blocks(out_path, blocks)


def write_country_setup(country_data: list, override_data: list):
    setup_dir_dict = defaultdict(list)

    # --- normal country setup ---
    for country in country_data:
        lines = [
            f"# {country['tag']} -> {ir_countries_dir.relative_to(ir_game)}/{country['setup_dir']}/{country['setup_file']}",
            f"color = {convert_color(country['color'])}",
            f"culture_definition = {country['culture']}",
            f"religion_definition = {country['religion']}",
        ]
        setup_dir_dict[country["setup_dir"]].append((country["tag"], lines))

    for setup_dir, country_blocks in setup_dir_dict.items():
        out_path = iu_countries / f"00_ir_{setup_dir}.txt"
        write_blocks(out_path, country_blocks)

    # --- overrides: COLLECT, THEN WRITE ONCE ---

    for path, countries in override_data.items():
        if path.name.endswith("_default.txt"):
            continue
        override_blocks = []
        for country in countries:
            lines = [
                f"# Override for {country['tag']}",
                f"color = {convert_color(country['color']) if isinstance(country['color'], _pydt.Tree) else country['color']}",
                f"culture_definition = {country['culture']}",
                f"religion_definition = {country['religion']}",
                f"is_historic = yes",
            ]
            override_blocks.append((country["tag"], lines))

        out_path = mod_root / path
        write_blocks(out_path, override_blocks)


from collections import OrderedDict


def write_localisation_files(
    culture_data: list,
    religion_data: list,
    country_data: list,
    character_data: list,
    dynasties: list,
):
    def sort_lines(lines: list[str]) -> list[str]:
        """Keep the first line (header) and sort the rest alphabetically."""
        return [lines[0]] + sorted(lines[1:])

    def remove_duplicate_keys(lines: list[str]) -> list[str]:
        """Remove duplicate keys, keeping only the first occurrence."""
        header, *body = lines
        seen_keys = set()
        unique_lines = []
        for line in body:
            key = line.split(":", 1)[0].strip()
            if key not in seen_keys:
                seen_keys.add(key)
                unique_lines.append(line)
        return [header] + unique_lines

    # -------- Cultures --------
    culture_lines = ["l_english:"]
    for group in culture_data:
        culture_lines.append(f'  {group["tag"]}: "{group["name"]}"')
        culture_lines.append(f'  {group["tag"]}_desc: "{group["name_desc"]}"')
        for culture in group["cultures"]:
            culture_lines.append(f'  {culture["tag"]}: "{culture["name"]}"')
    culture_lines = remove_duplicate_keys(sort_lines(culture_lines))

    # -------- Religions --------
    religion_lines = ["l_english:"]
    religion_lines.extend(
        [
            '  ir_religion_group: "Religions"',
            '  ir_religion_group_ADJ: "Religious"',
            '  ir_religion_group_desc: "Imperator Universalis Religions"',
        ]
    )
    for religion in religion_data:
        religion_lines.append(f'  {religion["tag"]}: "{religion["name"]}"')
        religion_lines.append(f'  {religion["tag"]}_ADJ: "{religion["name"]}"')
        religion_lines.append(f'  {religion["tag"]}_desc: "{religion["name_desc"]}"')
    religion_lines = remove_duplicate_keys(sort_lines(religion_lines))

    # -------- Countries --------
    country_lines = ["l_english:"]
    for country in country_data:
        country_lines.append(f'  {country["tag"]}: "{country["name"]}"')
        country_lines.append(f'  {country["tag"]}_ADJ: "{country["name_adj"]}"')
    country_lines = remove_duplicate_keys(sort_lines(country_lines))

    # -------- Characters --------
    character_lines = ["l_english:"]
    character_lines.extend(f'  {c["name_tag"]}: "{c["name"]}"' for c in character_data)
    character_lines.extend(
        f'  {c["nickname_tag"]}: "{c["nickname"]}"'
        for c in character_data
        if c.get("nickname")
    )
    character_lines = remove_duplicate_keys(sort_lines(character_lines))

    # -------- Dynasties --------
    dynasty_lines = ["l_english:"]
    for d in dynasties:
        dynasty_lines.append(f'  {d["tag"]}: "{d["name"]}"')
    dynasty_lines = remove_duplicate_keys(sort_lines(dynasty_lines))

    # -------- Write Files --------
    write_blocks(iu_localisation / "ir_cultures_l_english.yml", culture_lines)
    write_blocks(iu_localisation / "ir_religions_l_english.yml", religion_lines)
    write_blocks(iu_localisation / "ir_countries_l_english.yml", country_lines)
    write_blocks(iu_localisation / "ir_characters_l_english.yml", character_lines)
    write_blocks(iu_localisation / "ir_dynasties_l_english.yml", dynasty_lines)


def write_coa_file(coa_data: _pydt.Tree):
    write_blocks(iu_prescripted_coa, coa_data)


def _build_location_to_province_map(tree) -> dict:
    """Build a mapping from location -> province key by walking the eu5 map tree.

    The tree is a nested dict/Tree structure where the smallest keys are location
    identifiers and their parent is the province (the second-smallest tier).
    """
    mapping: dict = {}

    def walk(node, parent=None):
        # pyradox.Tree behaves like dict
        if isinstance(node, (_pydt.Tree, dict)):
            for k, v in node.items():
                if isinstance(v, (_pydt.Tree, dict)):
                    # k is a grouping key (could be province or higher); recurse
                    walk(v, k)
                elif isinstance(v, list):
                    # list of scalar locations or subtrees
                    for item in v:
                        if isinstance(item, (_pydt.Tree, dict)):
                            walk(item, k)
                        else:
                            mapping[str(item)] = k
                else:
                    # leaf value: k is likely a location name, parent is province
                    mapping[str(k)] = parent if parent is not None else k
        elif isinstance(node, list):
            for item in node:
                walk(item, parent)

    walk(tree, None)
    return mapping


def audit_country_locations(
    ten_countries_data: dict,
    country_data: list,
    eu5_map_data,
) -> None:
    """
    Audit own_control_core locations and capitals after writing 10_countries.

    Reports:
    - locations assigned to multiple country tags (only valid locations)
    - locations not present in the map (unknown)
    - capitals not present in the map (unknown)
    """

    location_to_province = (
        _build_location_to_province_map(eu5_map_data)
        if eu5_map_data is not None
        else {}
    )

    owners: dict[str, set[str]] = defaultdict(set)
    unknown_locations: list[tuple[str, str]] = []
    unknown_capitals: list[tuple[str, str]] = []

    for country in country_data:
        tag = country["tag"]
        base = ten_countries_data.get(tag, {})

        # --- own_control_core ---
        value = base.get("own_control_core", [])
        locations = (
            [] if value is None else value if isinstance(value, list) else [value]
        )

        for loc in locations:
            loc_key = str(loc)
            if loc_key not in location_to_province:
                unknown_locations.append((loc_key, tag))
            else:
                owners[loc_key].add(tag)

        # --- capital ---
        capital = base.get("capital")
        if capital:
            cap_key = str(capital)
            if cap_key not in location_to_province:
                unknown_capitals.append((cap_key, tag))
            else:
                owners[cap_key].add(tag)

    # --- REPORT ---
    conflicts = {loc: tags for loc, tags in owners.items() if len(tags) > 1}

    if not conflicts and not unknown_locations and not unknown_capitals:
        print(
            "Location audit: OK (no conflicts, no unknown locations, no unknown capitals)"
        )
        return

    print("\n=== LOCATION AUDIT REPORT ===")

    if conflicts:
        print("\nLocations assigned to multiple countries:")
        for loc, tags in sorted(conflicts.items()):
            print(f"  {loc}: {', '.join(sorted(tags))}")

    if unknown_locations:
        print("\nUnknown locations (own_control_core):")
        for loc, tag in sorted(unknown_locations):
            print(f"  {loc}: assigned to {tag}")

    if unknown_capitals:
        print("\nUnknown capitals:")
        for loc, tag in sorted(unknown_capitals):
            print(f"  {loc}: capital of {tag}")

    print("\n=== END LOCATION AUDIT ===\n")


def write_blocks_with_comments(
    out_path: Path,
    blocks: List[Tuple[str, List[object]]],
    comment_tags: set[str] | None = None,
    mode: str = "w",
    encoding: str = "utf-8",
    indent_str: str = "    ",
) -> Path:
    if comment_tags is None:
        comment_tags = set()

    def render_block(tag: str, lines: list, level: int = 0) -> list[str]:
        prefix = indent_str * level
        inner_prefix = indent_str * (level + 1)
        output: list[str] = []

        # Check if we need to comment out this entire block
        comment_block = tag in comment_tags

        # Opening line
        open_line = f"{prefix}{tag} = {{"
        if comment_block:
            open_line = "# " + open_line
        output.append(open_line)

        for line in lines:
            if isinstance(line, tuple) and len(line) == 2:
                subtag, sublines = line
                sublines_rendered = render_block(subtag, sublines, level + 1)
                if comment_block:
                    # Prefix every line of sub-block
                    sublines_rendered = [
                        f"# {l}" if not l.startswith("#") else l
                        for l in sublines_rendered
                    ]
                output.extend(sublines_rendered)
            else:
                l = f"{inner_prefix}{line}"
                if comment_block:
                    l = "# " + l if not l.startswith("#") else l
                output.append(l)

        # Closing brace
        close_line = f"{prefix}}}"
        if comment_block:
            close_line = "# " + close_line
        output.append(close_line)

        return output

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open(mode, encoding=encoding) as f:
        for block in blocks:
            if isinstance(block, tuple) and len(block) == 2:
                tag, lines = block
                rendered_lines = render_block(tag, lines, level=0)
                f.write("\n".join(rendered_lines) + "\n")
            else:
                # raw string block
                s = str(block)
                f.write(s)
                if not s.endswith("\n"):
                    f.write("\n")

    print_written("file", out_path)
    return out_path


def write_10_countries(
    ten_countries_data,
    country_data,
    eu5_map_data,
    country_rulers,
    culture_data=None,
    ir_country_locations=None,
    id_to_key=None,
    location_keys=None,
):
    country_map = {country["tag"]: country for country in country_data}
    blocks = []
    comment_tags = set()

    culture_to_group = {}
    if culture_data:
        for group in culture_data:
            group_tag = group.get("tag")
            for culture in group.get("cultures", []):
                culture_to_group[culture.get("tag")] = group_tag

    # build province mapping if provided
    location_to_province = (
        _build_location_to_province_map(eu5_map_data)
        if eu5_map_data is not None
        else {}
    )

    def normalize_value(value):
        if isinstance(value, str):
            v = value.strip()
            if len(v) >= 2 and v[0] == '"' and v[-1] == '"':
                return v[1:-1]
            return v
        return value

    for country in country_data:
        tag = country["tag"]
        country_name = country.get("name", tag)
        government_type = government_map[country_map[tag]["government"]]
        ruler = country_rulers.get(tag)  # optional override

        # --- start from base, preserve everything ---
        base = ten_countries_data.get(tag, {})
        merged = dict(base)  # shallow copy

        # --- own_control_core ---
        ir_locations = None
        if ir_country_locations and id_to_key and tag in ir_country_locations:
            ir_locations = []
            for pid in ir_country_locations[tag]:
                if pid in id_to_key:
                    loc = id_to_key.get(pid)
                    if loc is None:
                        continue
                    if location_keys is None or loc in location_keys:
                        ir_locations.append(loc)
        if ir_locations is not None:
            locations = ir_locations
        else:
            value = base.get("own_control_core", [])
            locations = (
                [] if value is None else value if isinstance(value, list) else [value]
            )

        if not locations:
            comment_tags.add(tag)
            # force inline empty block
            merged["own_control_core"] = "{ }"
        else:
            prov_map: dict[str, list] = {}
            used_locations = set()  # track all locations globally

            for loc in locations:
                key = str(loc)
                if key in used_locations:
                    continue  # skip duplicates across provinces
                prov = location_to_province.get(key, "unknown")
                prov_map.setdefault(prov, []).append(key)
                used_locations.add(key)

            own_sublines: list[str] = []
            for prov, locs in sorted(prov_map.items()):
                own_sublines.append(f"# {prov}")
                own_sublines.append(" ".join(locs))

            merged["own_control_core"] = own_sublines

        # --- government (merge, override ruler if exists) ---
        base_government = base.get("government", {})
        merged_government = dict(base_government)  # copy existing fields

        if ruler:
            merged_government["ruler"] = ruler
        else:
            merged_government["ruler"] = base_government.get("ruler", "random")

        merged_government["type"] = government_type

        # --- include IR-specific starting government reform if available ---
        try:
            ir_gov_key = country_map[tag]["government"]
        except Exception:
            ir_gov_key = None

        if ir_gov_key:
            reform_id = f"ir_{ir_gov_key}"
            raw = merged_government.get("reforms", [])
            normalized = [str(item) for item in ensure_list(raw) if item not in (None, "")]

            normalized.append(reform_id)
            seen = set()
            deduped = []
            for r in normalized:
                if r not in seen:
                    seen.add(r)
                    deduped.append(r)

            merged_government["reforms"] = deduped

        merged["government"] = merged_government

        # --- court language ---
        culture_tag = country.get("culture")
        if culture_tag:
            court_language = ir_culture_language_overrides.get(culture_tag)
            if not court_language:
                group_tag = culture_to_group.get(culture_tag)
                if group_tag:
                    court_language = ir_culture_group_language_map.get(group_tag)
            if court_language:
                merged["court_language"] = court_language

        # --- include societal values template based on IR government type ---
        societal_template_keys = {
            "aristocratic_monarchy",
            "despotic_monarchy",
            "stratocratic_monarchy",
            "theocratic_monarchy",
            "aristocratic_republic",
            "democratic_republic",
            "oligarchic_republic",
            "plutocratic_republic",
            "tribal_chiefdom",
            "tribal_federation",
            "tribal_kingdom",
        }

        # --- includes (preserve all, normalize) ---
        raw_include = base.get("include", [])
        include_items = raw_include if isinstance(raw_include, list) else [raw_include]

        if "expl_imperator_rome" not in include_items:
            include_items = ["expl_imperator_rome", *include_items]

        if ir_gov_key in societal_template_keys:
            societal_template = f"ir_{ir_gov_key}"
            if societal_template not in include_items:
                include_items = ["expl_imperator_rome", societal_template] + [
                    x for x in include_items if x != "expl_imperator_rome"
                ]

        merged["include"] = include_items

        # --- simple defaults ---
        merged.setdefault("country_rank", "rank_county")
        merged.setdefault("capital", "REPLACE_ME")

        # --- ensure capital is a valid location ---
        if locations:
            cap = merged.get("capital")
            if cap in ("REPLACE_ME", None) or (
                location_keys is not None and cap not in location_keys
            ):
                merged["capital"] = locations[0]

        # --- emit ---
        lines: list = []
        lines.append(f"# {country_name}")

        for key, value in merged.items():
            if key == "include":
                for x in value:
                    lines.append(f'include = "{x}"')

            elif isinstance(value, dict):
                sub = []
                for k, v in value.items():
                    if isinstance(v, list):
                        sub.append((k, v))
                    else:
                        sub.append(f"{k} = {normalize_value(v)}")
                lines.append((key, sub))

            elif isinstance(value, list):
                lines.append((key, value))

            else:
                # strings, numbers, AND inline "{ }"
                lines.append(f"{key} = {normalize_value(value)}")

        blocks.append((tag, lines))

    nested = ("countries", [("countries", blocks)])
    top_line = "current_age = age_1_traditions"

    write_blocks_with_comments(
        iu_setup_start / "10_countries.txt",
        [top_line, nested],
        comment_tags=comment_tags,
    )

    # --- audit pass ---
    audit_country_locations(ten_countries_data, country_data, eu5_map_data)


def write_05_characters(five_characters_data, character_data):
    # --- helpers ---
    char_by_id = {c["id"]: c for c in character_data}
    character_map = {c["id"]: c["tag"] for c in character_data}

    # --- build parent dependencies ---
    deps = defaultdict(set)
    for c in character_data:
        cid = c["id"]
        if c.get("father"):
            deps[cid].add(c["father"])
        if c.get("mother"):
            deps[cid].add(c["mother"])

    # --- topological sort (parents first) ---
    indeg = {c["id"]: 0 for c in character_data}
    for child, parents in deps.items():
        indeg[child] += len(parents)

    queue = [cid for cid, d in indeg.items() if d == 0]
    topo_order = []

    while queue:
        cid = queue.pop(0)
        topo_order.append(cid)
        for c, parents in deps.items():
            if cid in parents:
                indeg[c] -= 1
                if indeg[c] == 0:
                    queue.append(c)

    # --- enforce spouse adjacency ---
    used = set()
    final_order = []

    for cid in topo_order:
        if cid in used:
            continue

        c = char_by_id[cid]
        spouse = c.get("spouse")

        if spouse and spouse not in used:
            final_order.append(cid)
            final_order.append(spouse)
            used.add(cid)
            used.add(spouse)
        else:
            final_order.append(cid)
            used.add(cid)

    # --- emit blocks ---
    blocks = []
    comment_tags = set()
    spouse_emitted = set()

    for cid in final_order:
        character = char_by_id[cid]

        tag = character["tag"]
        name = character["name"]
        name_tag = character["name_tag"]
        dynasty = character["dynasty_tag"]

        # --- start from base, preserve everything ---
        base = five_characters_data.get(tag, {})
        merged = dict(base)

        if name_tag:
            merged["first_name"] = f"{{ name = {name_tag} }}"
        else:
            merged["first_name"] = "random"

        if dynasty:
            merged["dynasty"] = dynasty

        # --- relations ---
        if character.get("father"):
            merged["father"] = character_map[character["father"]]
        if character.get("mother"):
            merged["mother"] = character_map[character["mother"]]

        if character.get("spouse") and cid not in spouse_emitted:
            merged["spouse"] = character_map[character["spouse"]]
            spouse_emitted.add(character["spouse"])

        # --- attributes ---
        if character.get("culture"):
            merged["culture"] = character["culture"]
        if character.get("female"):
            merged["female"] = "yes"
        if character.get("religion"):
            merged["religion"] = character["religion"]

        merged["tag"] = character["country"]
        merged["birth_date"] = character["birth_date"]
        if "death_date" in character and character["death_date"]:
            merged["death_date"] = character["death_date"]

        if character.get("nickname_tag"):
            merged["nickname"] = character["nickname_tag"]

        # --- emit ---
        lines = []
        comment = f"# {name}"
        if dynasty:
            comment += dynasty
        lines.append(comment)

        for key, value in merged.items():
            if isinstance(value, dict):
                sub = [f"{k} = {v}" for k, v in value.items()]
                lines.append((key, sub))
            elif isinstance(value, list):
                lines.append((key, value))
            else:
                lines.append(f"{key} = {value}")

        blocks.append((tag, lines))

    nested = ("character_db", blocks)

    write_blocks_with_comments(
        iu_setup_start / "05_characters.txt",
        [nested],
        comment_tags=comment_tags,
    )


def write_04_dynasties(four_dynasties_data: dict, dynasties_data: list[dict]):
    blocks = []
    comment_tags = set()

    # --- merge new dynasties into existing dict ---
    for dynasty in dynasties_data:
        dynasty_tag = dynasty["tag"]

        # start from existing base if present
        base = four_dynasties_data.get(dynasty_tag, {})
        merged = dict(base)

        # override/add new fields
        merged.update(dynasty)

        # convert 'name' to single-level nested like default_dynasty
        merged["name"] = f"{{ name = {dynasty_tag} }}"

        # store back
        four_dynasties_data[dynasty_tag] = merged

    # --- emit all dynasties ---
    for dynasty_tag in sorted(four_dynasties_data):
        dynasty = four_dynasties_data[dynasty_tag]
        lines = []

        for key, value in dynasty.items():
            if key == "tag":
                continue  # skip tag entirely
            elif isinstance(value, dict):
                sub = [f"{k} = {v}" for k, v in value.items()]
                lines.append((key, sub))
            elif isinstance(value, list):
                lines.append((key, value))
            else:
                # simple scalar, including name
                lines.append(f"{key} = {value}")

        blocks.append((dynasty_tag, lines))

    nested = ("dynasty_manager", blocks)

    write_blocks_with_comments(
        iu_setup_start / "04_dynasties.txt",
        [nested],
        comment_tags=comment_tags,
    )


def write_12_diplomacy(twelve_diplomacy_data: dict, diplomatic_relationships: list):
    blocks = []
    comment_tags = set()

    for relationship in diplomatic_relationships:
        attrs = " ".join(
            f"{key} = {value}" for key, value in relationship.items() if key != "tag"
        )
        block = f"{relationship['tag']} = {{ {attrs} }}"
        blocks.append(block)

    nested = ("diplomacy_manager", blocks)

    write_blocks_with_comments(
        iu_setup_start / "12_diplomacy.txt",
        [nested],
        comment_tags=comment_tags,
    )


def write_15_international_organizations(
    fifteen_international_organizations_data: dict,
    international_organizations: list,
):
    blocks = []
    comment_tags = set()

    for io in international_organizations:
        type = io["type"]
        members = " ".join(io["members"])
        block = (
            "add_international_organization",
            [f"type = {type}", f"members = {{ {members} }}"],
        )
        blocks.append(block)

    nested = ("international_organization_manager", blocks)

    write_blocks_with_comments(
        iu_setup_start / "15_international_organizations.txt",
        [nested],
        comment_tags=comment_tags,
    )
