import os
import re
import shutil
from collections import defaultdict
from pathlib import Path
from typing import List, Tuple, Union

import pyradox
import pyradox.datatype as _pydt
import pyradox.token as _pytoken

from .data import (
    government_map,
    ir_culture_group_language_map,
    ir_culture_group_base_language_map,
    ir_language_base_color_map,
    ir_culture_language_overrides,
    ir_language_dialect_parent_map,
    ir_culture_group_graphical_map,
    ir_culture_graphical_overrides,
    formable_requirement_overrides,
    formable_localization_overrides,
    formable_alias_target_overrides,
    disabled_formable_tags,
)
from .paths import *

pyradox.Color = _pydt.Color
pyradox.Tree = _pydt.Tree

AUTO_GENERATED_HEADER = (
    "# =========================================================== #\n"
    "#            THIS FILE IS AUTOMATICALLY GENERATED!            #\n"
    "#  Any manual changes will be OVERWRITTEN upon regeneration!  #\n"
    "# =========================================================== #\n\n"
)


def ensure_list(value):
    return value if isinstance(value, list) else [value]


def _dedupe(items: list) -> list:
    seen = set()
    out = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        out.append(item)
    return out


def _base_name_from_group_tag(tag: str) -> str:
    name = tag
    if name.startswith("ir_"):
        name = name[3:]
    if name.endswith("_g"):
        name = name[:-2]
    if name.endswith("_group"):
        name = name[:-6]
    return name


def _language_id_from_group_tag(tag: str) -> str:
    return f"ir_{_base_name_from_group_tag(tag)}_lang"


def _language_family_id_from_group_tag(tag: str) -> str:
    return f"ir_{_base_name_from_group_tag(tag)}_family"


# NOTE: Regex-based block parsing has been removed. Use pyradox instead.


def _language_to_dialect_id(lang_id: str | None) -> str | None:
    if not lang_id:
        return None
    if lang_id in ir_language_dialect_parent_map:
        return (
            lang_id.replace("_lang", "_dialect")
            if lang_id.endswith("_lang")
            else f"{lang_id}_dialect"
        )
    return lang_id


def _dialect_parent_language(lang_or_dialect: str | None) -> str | None:
    if not lang_or_dialect:
        return None
    if lang_or_dialect in ir_language_dialect_parent_map:
        return ir_language_dialect_parent_map[lang_or_dialect]
    if lang_or_dialect.endswith("_dialect"):
        candidate = lang_or_dialect.replace("_dialect", "_lang")
        return ir_language_dialect_parent_map.get(candidate, candidate)
    return lang_or_dialect


def _language_family_map_from_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    from .extract_data import parse_tree

    tree = parse_tree(path)
    family_map: dict[str, str] = {}
    for lang_id, value in tree.items():
        block = value
        if isinstance(value, list) and value:
            block = value[0]
        if not isinstance(block, _pydt.Tree):
            continue
        fam = block.find("family")
        if isinstance(fam, list):
            fam = fam[0] if fam else ""
        family_map[lang_id] = str(fam) if fam else ""
    return family_map


def write_language_data_full(culture_data: list) -> None:
    """Ensure ir_languages.txt contains blocks for every IU language used."""
    out_path = iu_languages / "ir_languages.txt"
    from .extract_data import parse_tree
    import copy

    existing_tree = parse_tree(out_path) if out_path.exists() else _pydt.Tree()

    # Determine all language IDs that should exist.
    language_ids_raw = set(ir_culture_group_language_map.values())
    language_ids_raw.update(ir_culture_language_overrides.values())
    language_ids_raw.update(ir_language_base_color_map.keys())
    # Map dialect languages to their parent language.
    language_ids = {
        _dialect_parent_language(lang_id)
        for lang_id in language_ids_raw
        if lang_id
    }

    # Map language -> culture group (from culture data + group-language map)
    lang_groups: dict[str, set[str]] = defaultdict(set)
    for group in culture_data:
        group_tag = group.get("tag")
        for culture in group.get("cultures", []):
            culture_tag = culture.get("tag")
            culture_language = None
            if culture_tag:
                culture_language = ir_culture_language_overrides.get(culture_tag)
            if not culture_language and group_tag:
                culture_language = ir_culture_group_language_map.get(group_tag)
            # For group mapping, store the parent language (dialect parent).
            culture_language = _dialect_parent_language(culture_language)
            if culture_language and group_tag:
                lang_groups[culture_language].add(group_tag)
    # Ensure every group-mapped language retains a group association,
    # even if all cultures are overridden to sub-languages.
    for group_tag, lang_id in ir_culture_group_language_map.items():
        if group_tag and lang_id:
            lang_id = _dialect_parent_language(lang_id)
            lang_groups[lang_id].add(group_tag)

    # Build cache of base-game language blocks for reuse using pyradox.
    base_language_blocks: dict[str, _pydt.Tree] = {}
    base_languages_dir = eu5_game / "in_game" / "common" / "languages"
    if base_languages_dir.exists():
        for path in sorted(base_languages_dir.glob("*.txt")):
            tree = parse_tree(path)
            for base_key in set(ir_language_base_color_map.values()) | set(
                ir_culture_group_base_language_map.values()
            ):
                if base_key in base_language_blocks:
                    continue
                if base_key in tree:
                    block = tree[base_key]
                    if isinstance(block, list) and block:
                        block = block[0]
                    if isinstance(block, _pydt.Tree):
                        base_language_blocks[base_key] = block

    def infer_family(lang_id: str) -> str:
        groups = lang_groups.get(lang_id)
        if groups:
            group_tag = sorted(groups)[0]
            return _language_family_id_from_group_tag(group_tag)
        return ""

    def infer_base_key(lang_id: str) -> str | None:
        base_key = ir_language_base_color_map.get(lang_id)
        if base_key:
            return base_key
        groups = lang_groups.get(lang_id)
        if not groups:
            return None
        group_tag = sorted(groups)[0]
        return ir_culture_group_base_language_map.get(group_tag)

    # Parent language -> list of dialect source language IDs.
    parent_to_dialects: dict[str, list[str]] = defaultdict(list)
    for child_lang, parent_lang in ir_language_dialect_parent_map.items():
        if parent_lang:
            parent_to_dialects[parent_lang].append(child_lang)

    out_tree = _pydt.Tree()
    for lang_id in sorted(language_ids):
        block = existing_tree[lang_id] if lang_id in existing_tree else None
        if isinstance(block, list) and block:
            block = block[0]
        base_key = infer_base_key(lang_id)
        base_block = (
            copy.deepcopy(base_language_blocks[base_key])
            if base_key and base_key in base_language_blocks
            else None
        )

        def is_placeholder(tree: _pydt.Tree) -> bool:
            keys = {k for k, _ in tree.items()}
            return keys.issubset({"color", "family"})

        if isinstance(block, _pydt.Tree) and not is_placeholder(block):
            out_block = copy.deepcopy(block)
        elif base_block is not None:
            out_block = base_block
        elif isinstance(block, _pydt.Tree):
            out_block = copy.deepcopy(block)
        else:
            out_block = _pydt.Tree()
            out_block["color"] = _pydt.Color("rgb", [128, 128, 128])

        # Remove copied dialects to avoid duplicate dialect IDs across languages.
        if "dialects" in out_block:
            del out_block["dialects"]

        # Add IU dialects when configured.
        dialect_children = parent_to_dialects.get(lang_id, [])
        if dialect_children:
            dialects_tree = _pydt.Tree()
            for child_lang in sorted(dialect_children):
                dialect_id = (
                    child_lang.replace("_lang", "_dialect")
                    if child_lang.endswith("_lang")
                    else f"{child_lang}_dialect"
                )
                dialects_tree.append(dialect_id, _pydt.Tree())
            out_block["dialects"] = dialects_tree

        family_id = infer_family(lang_id)
        if family_id:
            # Always override to ensure IU family IDs are used.
            out_block["family"] = family_id

        out_tree[lang_id] = out_block

    # Write with a manual header; do NOT auto-generate elsewhere.
    header = (
        "# =========================================================== #\n"
        "#         THIS FILE IS MANUALLY CURATED. DO NOT              #\n"
        "#           AUTO-GENERATE OR OVERWRITE.                      #\n"
        "# =========================================================== #\n\n"
    )
    blocks = convert_tree_to_blocks(out_tree)
    content = [header]
    for block in blocks:
        if isinstance(block, tuple) and len(block) == 2:
            tag, lines = block
            content.append(make_block(tag, lines, indent_level=0, indent_str="    "))
            content.append("\n")
        else:
            content.append(str(block))
            if not str(block).endswith("\n"):
                content.append("\n")
            content.append("\n")
    out_path.write_text("".join(content), encoding="utf-8-sig")
    print_written("file", out_path)
def print_written(kind: str, out_path: Path) -> None:
    """Print a concise relative write message for `out_path`.

    `kind` should be a short label like 'file', 'JSON', 'CSV', or 'image'.
    """
    try:
        rel = os.path.relpath(str(out_path), start=str(mod_root))
    except Exception:
        rel = str(out_path)
    print(f"Writing {kind}: {rel}")


def convert_color(color: _pydt.Color) -> str:
    if color.colorspace == "rgb":
        r, g, b = color.channels
        return f"rgb {{ {r} {g} {b} }}"
    elif color.colorspace == "hsv":
        h, s, v = color.channels
        return f"hsv {{ {h:.2f} {s:.2f} {v:.2f} }}"
    else:
        raise ValueError(f"Unsupported color space: {color.colorspace}")


def convert_tree_to_blocks(
    tree: _pydt.Tree,
) -> List[Union[str, Tuple[str, List[object]]]]:
    blocks: List[Union[str, Tuple[str, List[object]]]] = []

    grouped: dict[str, list] = {}

    # Group repeated keys
    for key, value in tree.items():
        if key not in grouped:
            grouped[key] = []
        grouped[key].append(value)

    for key, values in grouped.items():
        # All scalar values → aggregate into one line
        if all(not isinstance(v, (_pydt.Tree, list)) for v in values):
            formatted_values = [_pytoken.make_token_string(v) for v in values]
            if len(formatted_values) == 1:
                blocks.append(f"{key} = {formatted_values[0]}")
            else:
                items = " ".join(formatted_values)
                blocks.append(f"{key} = {{ {items} }}")
            continue

        # Lists of scalars → emit a single brace block
        if all(isinstance(v, list) for v in values):
            flat: list[object] = []
            has_complex = False
            for v in values:
                for item in v:
                    if isinstance(item, (_pydt.Tree, list)):
                        has_complex = True
                        break
                    flat.append(item)
                if has_complex:
                    break
            if not has_complex:
                formatted = " ".join(_pytoken.make_token_string(item) for item in flat)
                blocks.append(f"{key} = {{ {formatted} }}")
                continue

        # Complex values: trees or lists
        for v in values:
            if isinstance(v, _pydt.Tree):
                # Use the parent key as the tag, not the "tag" inside the tree
                subblocks = convert_tree_to_blocks(v)
                blocks.append((key, subblocks))
            elif isinstance(v, list):
                for item in v:
                    if isinstance(item, _pydt.Tree):
                        # Again, parent key is used to avoid double nesting
                        subblocks = convert_tree_to_blocks(item)
                        blocks.append((key, subblocks))
                    else:
                        # Scalar inside a list
                        formatted = _pytoken.make_token_string(item)
                        blocks.append(f"{key} = {formatted}")

    return blocks


def make_block(
    tag: str,
    lines: List[Union[str, Tuple[str, List[object]]]] | None = None,
    indent_level: int = 0,
    indent_str: str = "    ",
) -> str:
    if lines is None:
        lines = []

    prefix = indent_str * indent_level
    inner_prefix = prefix + indent_str

    parts: List[str] = [f"{prefix}{tag} = {{\n"]

    for line in lines:
        if isinstance(line, tuple) and len(line) == 2:
            subtag, sublines = line
            parts.append(make_block(subtag, sublines, indent_level + 1, indent_str))
        else:
            parts.append(f"{inner_prefix}{line}\n")

    parts.append(f"{prefix}}}\n")
    return "".join(parts)


def write_blocks(
    out_path: Path,
    blocks: Union[
        str,
        Tuple[str, List[object]],
        List[Union[str, Tuple[str, List[object]]]],
    ],
    mode: str = "w",
    encoding: str = "utf-8-sig",
    indent_str: str = "    ",
) -> Path:
    # normalize to a list of blocks
    if isinstance(blocks, (tuple, str)):
        blocks_list = [blocks]
    elif isinstance(blocks, list):
        blocks_list = blocks
    elif isinstance(blocks, _pydt.Tree):
        blocks_list = convert_tree_to_blocks(blocks)
    else:
        raise TypeError("blocks must be a str, a (tag, lines) tuple, or a list")

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open(mode, encoding=encoding) as f:
        # --- header ---
        f.write(AUTO_GENERATED_HEADER)

        for block in blocks_list:
            if isinstance(block, tuple) and len(block) == 2:
                tag, lines = block
                content = make_block(tag, lines, indent_level=0, indent_str=indent_str)
                # Collapse accidental double-empty-brace sequences (e.g. "{ {} }")
                content = content.replace("{ {} }", "{}")
                f.write(content)
                f.write("\n")
            else:
                s = str(block)
                s = s.replace("{ {} }", "{}")
                f.write(s)
                if not s.endswith("\n"):
                    f.write("\n")
                if out_path.suffix not in (".yml", ".yaml"):
                    f.write("\n")

    print_written("file", out_path)
    return out_path


def _existing_block_map(path: Path) -> dict[str, _pydt.Tree]:
    return {}


def _merge_tree_with_overrides(
    existing: _pydt.Tree | None,
    overrides: dict[str, object],
    add_if_missing: dict[str, object] | None = None,
) -> _pydt.Tree:
    merged = _pydt.Tree(existing) if existing is not None else _pydt.Tree()
    for key, value in overrides.items():
        merged[key] = value
    if add_if_missing:
        for key, value in add_if_missing.items():
            if key not in merged:
                merged.append(key, value)
    return merged


def _append_existing_blocks(
    blocks: list,
    existing_blocks: dict[str, _pydt.Tree],
    generated_tags: set[str],
) -> None:
    for tag, tree in existing_blocks.items():
        if tag not in generated_tags:
            lines = convert_tree_to_blocks(tree)
            blocks.append((tag, lines))


def _map_religion(raw_religion: str | None, religion_tags: set[str]) -> str | None:
    mapped = PANTHEON_MAP.get(raw_religion)
    if not mapped and raw_religion:
        candidate = f"ir_{raw_religion}"
        if candidate in religion_tags:
            mapped = candidate
    return mapped


def _build_country_rank_map(
    ir_country_locations: dict[str, list[int]],
    country_data: list[dict] | None = None,
) -> dict[str, str]:
    sizes = {tag: len(locs) for tag, locs in ir_country_locations.items()}
    if not sizes:
        return {}

    county_max = 3
    duchy_max = 14
    kingdom_max = 249

    government_by_tag: dict[str, str] = {}
    if country_data:
        for country in country_data:
            tag = country.get("tag")
            if tag:
                government_by_tag[tag] = country.get("government")

    monarchies = {
        "aristocratic_monarchy",
        "despotic_monarchy",
        "stratocratic_monarchy",
        "plutocratic_monarchy",
        "spartan_monarchy",
        "tribal_kingdom"
    }

    rank_map: dict[str, str] = {}
    for tag, size in sizes.items():
        if size <= county_max:
            rank = "rank_county"
        elif size <= duchy_max:
            rank = "rank_duchy"
        elif size <= kingdom_max:
            rank = "rank_kingdom"
        else:
            rank = "rank_empire"
        ir_gov = government_by_tag.get(tag)
        if ir_gov in monarchies:
            if rank in ("rank_county", "rank_duchy"):
                rank = "rank_kingdom"

        rank_map[tag] = rank

    return rank_map


def write_culture_group_data(culture_data: list):
    blocks = [(culture_group["tag"], []) for culture_group in culture_data]
    out_path = iu_culture_groups / f"ir_culture_groups.txt"
    write_blocks(out_path, blocks)


def write_culture_data(culture_data: list):
    for culture_group in culture_data:
        blocks = []

        def resolve_gfx_tags(value):
            tags = ensure_list(value) if value is not None else []
            resolved: list[str] = []
            for tag in tags:
                if isinstance(tag, str) and tag.startswith("ir_") and tag.endswith("_gfx"):
                    continue
                resolved.append(tag)
            return _dedupe(resolved)

        group_tag = culture_group.get("tag")
        group_gfx = None
        if group_tag:
            group_gfx = ir_culture_group_graphical_map.get(group_tag)
        if not group_gfx:
            group_gfx = culture_group["graphical_culture"]

        group_gfx = resolve_gfx_tags(group_gfx)

        for culture in culture_group["cultures"]:
            culture_tag = culture.get("tag")
            gfx_tag = (
                ir_culture_graphical_overrides.get(culture_tag)
                if culture_tag
                else None
            )
            if not gfx_tag:
                gfx_tag = group_gfx

            gfx_tags = resolve_gfx_tags(gfx_tag)
            gfx_tags_str = " ".join(gfx_tags)

            culture_language = None
            if culture_tag:
                culture_language = ir_culture_language_overrides.get(culture_tag)
            if not culture_language and group_tag:
                culture_language = ir_culture_group_language_map.get(group_tag)
            if culture_language:
                culture_language = _language_to_dialect_id(culture_language)

            lines = []
            if culture_language:
                lines.append(f"language = {culture_language}")
            lines.extend(
                [
                    f"color = {culture_group['color']}",
                    f"tags = {{ {gfx_tags_str} }}",
                    f"culture_groups = {{ {culture_group['tag']} }}",
                ]
            )

            blocks.append((culture["tag"], lines))

        out_path = iu_cultures / f"{culture_group['tag']}.txt"

        write_blocks(out_path, blocks)


def write_language_family_data(culture_data: list) -> None:
    blocks = []
    for culture_group in culture_data:
        group_tag = culture_group.get("tag")
        if not group_tag:
            continue
        family_id = _language_family_id_from_group_tag(group_tag)
        blocks.append((family_id, [f"color = {culture_group['color']}"]))

    out_path = iu_language_families / "ir_language_families.txt"
    write_blocks(out_path, blocks)


def write_language_data(culture_data: list) -> None:
    # Regex parsing is disallowed; delegate to pyradox-based writer.
    write_language_data_full(culture_data)


def write_culture_language_report(culture_data: list) -> None:
    """Write a TSV report of culture groups, cultures, languages, and families."""
    report_path = Path(__file__).parent / "ir_culture_language_report.tsv"
    family_map = _language_family_map_from_file(iu_languages / "ir_languages.txt")
    lines = ["culture_group_tag\tculture_group\tculture_tag\tculture\tlanguage\tlanguage_family"]
    for culture_group in culture_data:
        group_tag = culture_group.get("tag", "")
        group_name = culture_group.get("name", "")
        for culture in culture_group.get("cultures", []):
            culture_tag = culture.get("tag", "")
            culture_name = culture.get("name", "")
            culture_language = None
            if culture_tag:
                culture_language = ir_culture_language_overrides.get(culture_tag)
            if not culture_language and group_tag:
                culture_language = ir_culture_group_language_map.get(group_tag)
            culture_language = _language_to_dialect_id(culture_language)
            family_id = family_map.get(_dialect_parent_language(culture_language) or "", "")
            if not family_id and group_tag:
                family_id = _language_family_id_from_group_tag(group_tag)
            lines.append(
                f"{group_tag}\t{group_name}\t{culture_tag}\t{culture_name}\t"
                f"{culture_language or ''}\t{family_id}"
            )
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print_written("file", report_path)


RELIGION_GROUP_MAP = {
    "ir_roman_pantheon": "ir_hellenic_group",
    "ir_egyptian_pantheon": "ir_egyptian_group",
    "ir_carthaginian_pantheon": "ir_canaanite_group",
    "ir_mesopotamian_religion": "ir_mesopotamian_group",
    "ir_caucasian_religion": "ir_caucasian_group",
    "ir_armenian_religion": "ir_armenian_group",
    "ir_anatolian_religion": "ir_anatolian_group",
    "ir_druidism": "ir_celtic_group",
    "ir_animism": "ir_iberic_group",
    "ir_berber_religion": "ir_berber_group",
    "ir_germanic_religion": "ir_germanic_group",
    "ir_shamanism": "ir_shamanic_group",
    "ir_indo_iranian_religion": "ir_indo_iranian_group",
    "ir_arabian_pantheon": "ir_arabian_group",
    "ir_zoroaster": "ir_zoroastrian_group",
    "ir_judaism": "ir_israelite_group",
    "ir_buddhism": "ir_buddhist_group",
    "ir_hindu": "ir_dharmic_group",
    "ir_jainism": "ir_dharmic_group",
    "ir_eastern_animism": "ir_eastern_animist_group",
    "ir_bon_religion": "ir_eastern_animist_group",
    "ir_matrist_religion": "ir_eastern_animist_group",
    # Previously unmapped religions
    "ir_nuragic_pantheon": "ir_iberic_group",
    "ir_pre_indo_european_religion": "ir_iberic_group",
    "ir_italic_pantheon": "ir_hellenic_group",
    "ir_illyrian_pantheon": "ir_hellenic_group",
    "ir_hurrian_pantheon": "ir_mesopotamian_group",
    "ir_hatti_religion": "ir_anatolian_group",
    "ir_agama": "ir_dharmic_group",
    "ir_ajivika": "ir_dharmic_group",
    "ir_anahitic_religion": "ir_zoroastrian_group",
    "ir_mithra_religion": "ir_zoroastrian_group",
    "ir_vaksh_religion": "ir_zoroastrian_group",
    "ir_puntic_religion": "ir_egyptian_group",
    "ir_nilotic_pantheon": "ir_egyptian_group",
    "ir_uralic_pantheon": "ir_shamanic_group",
    "ir_burmese_religion": "ir_eastern_animist_group",
    "ir_circassian_pantheon": "ir_caucasian_group",
    "ir_chinese_religions": "ir_eastern_animist_group",
}

RELIGION_GROUP_NAMES = {
    "ir_hellenic_group": "Hellenic",
    "ir_egyptian_group": "Egyptian",
    "ir_canaanite_group": "Canaanite",
    "ir_mesopotamian_group": "Mesopotamian",
    "ir_caucasian_group": "Caucasian",
    "ir_armenian_group": "Armenian",
    "ir_anatolian_group": "Anatolian",
    "ir_celtic_group": "Celtic",
    "ir_iberic_group": "Iberic",
    "ir_berber_group": "Berber",
    "ir_germanic_group": "Germanic",
    "ir_shamanic_group": "Shamanic",
    "ir_indo_iranian_group": "Indo-Iranian",
    "ir_arabian_group": "Arabian",
    "ir_zoroastrian_group": "Zoroastrian",
    "ir_israelite_group": "Israelite",
    "ir_buddhist_group": "Buddhist",
    "ir_dharmic_group": "Dharmic",
    "ir_eastern_animist_group": "Eastern Animist",
}

PANTHEON_MAP = {
    "roman_pantheon": "ir_roman_pantheon",
    "egyptian_pantheon": "ir_egyptian_pantheon",
    "carthaginian_pantheon": "ir_carthaginian_pantheon",
    "shamanism": "ir_shamanism",
    "caucasian_religion": "ir_caucasian_religion",
    "mesopotamian_religion": "ir_mesopotamian_religion",
    "armenian_religion": "ir_armenian_religion",
    "anatolian_religion": "ir_anatolian_religion",
    "druidism": "ir_druidism",
    "animism": "ir_animism",
    "judaism": "ir_judaism",
    "zoroaster": "ir_zoroaster",
    "berber_religion": "ir_berber_religion",
    "germanic_religion": "ir_germanic_religion",
    "indo_iranian_religion": "ir_indo_iranian_religion",
    "arabian_pantheon": "ir_arabian_pantheon",
    "buddhism": "ir_buddhism",
    "hindu": "ir_hindu",
    "eastern_animism": "ir_eastern_animism",
    "bon_religion": "ir_bon_religion",
    "matrist_religion": "ir_matrist_religion",
    "jainism": "ir_jainism",
}

GOD_CATEGORY_MODIFIERS = {
    "war": {
        "land_morale_modifier": 0.05,
        "discipline": 0.01,
    },
    "economy": {
        "global_raw_material_output": 0.05,
        "trade_efficiency": 0.05,
    },
    "culture": {
        "research_speed_modifier": 0.05,
        "global_max_literacy": 2,
    },
    "fertility": {
        "global_population_growth": 0.0002,
        "global_monthly_food_modifier": 0.03,
    },
}

GOD_CATEGORY_ASPECT_ICONS = {
    "war": "religious_aspect_folk_red",
    "economy": "religious_aspect_folk_brown",
    "culture": "religious_aspect_folk_blue",
    "fertility": "religious_aspect_folk_pink",
}


def write_religion_group_data(religion_data: list):
    religion_color_map = {
        r.get("tag"): r.get("color") for r in religion_data if r.get("tag")
    }

    group_color_map: dict[str, _pydt.Color] = {}
    for religion_tag, group_tag in RELIGION_GROUP_MAP.items():
        if group_tag in group_color_map:
            continue
        color = religion_color_map.get(religion_tag)
        if color is not None:
            group_color_map[group_tag] = color

    blocks = []
    for group_tag in sorted(RELIGION_GROUP_NAMES.keys()):
        color = group_color_map.get(group_tag)
        if color is None:
            color = _pydt.Color("rgb", [255, 255, 255])
        blocks.append(
            (
                group_tag,
                [
                    f"color = {convert_color(color)}",
                ],
            )
        )

    blocks.append(
        (
            "ir_unknown_group",
            [
                "# Fallback group for unmapped religions",
                "color = rgb { 255 255 255 }",
            ],
        )
    )

    out_path = iu_religion_groups / "ir_default.txt"

    write_blocks(out_path, blocks)


def write_religion_data(religion_data: list):
    out_path = iu_religions / "ir_religions.txt"
    existing_blocks = _existing_block_map(out_path)

    blocks = []
    generated_tags: set[str] = set()

    for religion in religion_data:
        tag = religion["tag"]
        generated_tags.add(tag)

        overrides = {
            "color": religion["color"],
            "group": RELIGION_GROUP_MAP.get(tag, "ir_unknown_group"),
        }
        add_if_missing = {
            # Enable a single selectable aspect (Romuva-style pantheon mechanic).
            "religious_aspects": 1,
        }

        existing = existing_blocks.get(tag)
        merged_tree = _merge_tree_with_overrides(existing, overrides, add_if_missing)
        lines = convert_tree_to_blocks(merged_tree)
        blocks.append((tag, lines))

    _append_existing_blocks(blocks, existing_blocks, generated_tags)

    write_blocks(out_path, blocks)


def write_god_data(deity_data: list, religion_data: list):
    religion_tags = {r.get("tag") for r in religion_data if r.get("tag")}

    out_path = iu_gods / "00_ir_gods.txt"
    existing_blocks = _existing_block_map(out_path)

    blocks = []
    generated_tags: set[str] = set()
    for deity in sorted(deity_data, key=lambda d: d.get("tag", "")):
        deity_tag = deity.get("tag")
        if not deity_tag:
            continue
        generated_tags.add(deity_tag)
        raw_religion = deity.get("religion")
        mapped_religion = _map_religion(raw_religion, religion_tags)

        category = deity.get("category")
        modifiers = GOD_CATEGORY_MODIFIERS.get(category, GOD_CATEGORY_MODIFIERS["culture"])
        modifier_tree = _pydt.Tree({k: v for k, v in modifiers.items()})

        overrides: dict[str, object] = {
            "icon": "god_folk_blue",
            "country_modifier": modifier_tree,
        }
        if mapped_religion:
            overrides["religion"] = mapped_religion
            existing = existing_blocks.get(deity_tag)
            merged_tree = _merge_tree_with_overrides(existing, overrides)
        else:
            overrides["group"] = _pydt.Tree(
                {
                    "group": "ir_unknown_group",
                    "name_key": deity_tag,
                }
            )
            existing = existing_blocks.get(deity_tag)
            merged_tree = _merge_tree_with_overrides(existing, overrides)

        lines = convert_tree_to_blocks(merged_tree)
        blocks.append((deity_tag, lines))

    _append_existing_blocks(blocks, existing_blocks, generated_tags)

    write_blocks(out_path, blocks)


def write_ir_religious_aspects(deity_data: list, religion_data: list) -> None:
    out_path = iu_religious_aspects / "ir_folk_default.txt"
    existing_blocks = _existing_block_map(out_path)
    religion_tags = {r.get("tag") for r in religion_data if r.get("tag")}

    blocks = []
    generated_tags: set[str] = set()

    for deity in sorted(deity_data, key=lambda d: d.get("tag", "")):
        deity_tag = deity.get("tag")
        if not deity_tag:
            continue

        aspect_name = f"worship_{deity_tag}"
        generated_tags.add(aspect_name)

        raw_religion = deity.get("religion")
        mapped_religion = _map_religion(raw_religion, religion_tags)

        if not mapped_religion:
            print(f"Warning: missing religion mapping for deity {deity_tag}")
            continue

        category = deity.get("category")
        modifiers = GOD_CATEGORY_MODIFIERS.get(category, GOD_CATEGORY_MODIFIERS["culture"])
        icon = GOD_CATEGORY_ASPECT_ICONS.get(category, "religious_aspect_folk_blue")

        existing = existing_blocks.get(aspect_name)
        existing_religions: list[str] = []
        if existing is not None:
            existing_religions = [str(v) for v in existing.find_all("religion")]

        merged_religions = [mapped_religion] + [
            tag for tag in existing_religions if tag != mapped_religion
        ]

        merged_tree = _pydt.Tree()
        merged_tree.append("icon", icon)
        merged_tree.append("modifier", _pydt.Tree(modifiers))

        if existing is not None:
            for key, value in existing.items():
                if str(key) in {"icon", "modifier", "religion"}:
                    continue
                merged_tree.append(key, value)

        for tag in merged_religions:
            merged_tree.append("religion", tag)

        lines = convert_tree_to_blocks(merged_tree)
        blocks.append((aspect_name, lines))

    _append_existing_blocks(blocks, existing_blocks, generated_tags)

    write_blocks(out_path, blocks)


def write_country_setup(country_data: list, _override_data: list):
    setup_dir_dict = defaultdict(list)
    ir_countries_rel = ir_relative_display(ir_countries_dir)

    # --- normal country setup ---
    for country in country_data:
        lines = [
            f"# {country['tag']} -> {ir_countries_rel}/{country['setup_dir']}/{country['setup_file']}",
            f"color = {convert_color(country['color'])}",
            f"culture_definition = {country['culture']}",
            f"religion_definition = {country['religion']}",
        ]
        setup_dir_dict[country["setup_dir"]].append((country["tag"], lines))

    # Do not generate split ir_*.txt country files when using replace_paths.
    # Keep setup/countries driven by _countries.txt plus _default.txt only.
    for legacy in iu_countries.glob("ir_*.txt"):
        legacy.unlink()
        print(f"Removed legacy file: {legacy.relative_to(mod_root)}")

    # Register all country tags for replace_paths-driven country loading.
    # Provide full entries (not empty blocks) so tags are recognized as valid countries.
    by_tag = {country["tag"]: country for country in country_data if country.get("tag")}
    index_blocks = []
    for tag in sorted(by_tag.keys()):
        country = by_tag[tag]
        lines = [
            f"color = {convert_color(country['color'])}",
            f"culture_definition = {country['culture']}",
            f"religion_definition = {country['religion']}",
        ]
        index_blocks.append((tag, lines))

    # Keep base fallback country tags available as valid definitions.
    index_blocks.extend(
        [
            ("DUMMY", ["color = rgb { 40 40 40 }", "color2 = rgb { 110 27 27 }"]),
            ("PIR", ["color = rgb { 116 143 139 }", "color2 = rgb { 110 27 27 }"]),
            ("MER", ["color = rgb { 72 85 83 }", "color2 = rgb { 110 27 27 }"]),
        ]
    )
    write_blocks(iu_countries / "_countries.txt", index_blocks)

    # Keep EU5 fallback tags available in the replaced countries folder.
    base_default = eu5_game / "in_game" / "setup" / "countries" / "_default.txt"
    if base_default.exists():
        dst_default = iu_countries / "_default.txt"
        shutil.copy2(base_default, dst_default)
        print_written("file", dst_default)

    # Base-game country files are handled through metadata replace_paths.
    # Remove legacy per-file override placeholders from earlier converter runs.
    for path in _override_data.keys():
        if path.name.endswith("_default.txt"):
            continue
        legacy_path = mod_root / path
        if legacy_path.exists():
            legacy_path.unlink()
            print(f"Removed legacy file: {legacy_path.relative_to(mod_root)}")


def write_formable_countries(
    formable_data: dict[str, dict[str, object]],
    country_data: list,
    ir_country_locations: dict[str, list[int]],
    ir_country_capitals: dict[str, int],
    id_to_key: dict[int, str],
    eu5_map_data: dict | None,
) -> None:
    out_path = mod_root / "in_game" / "common" / "formable_countries" / "00_formable_countries.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    known_tags = {country.get("tag") for country in country_data if country.get("tag")}
    country_name_to_tag: dict[str, str] = {}

    def _normalize_name_key(value: object) -> str:
        if not isinstance(value, str):
            return ""
        lowered = value.strip().lower()
        if not lowered:
            return ""
        # Collapse non-alnum to single spaces for robust name matching.
        lowered = re.sub(r"[^a-z0-9]+", " ", lowered)
        return re.sub(r"\s+", " ", lowered).strip()

    for country in country_data:
        ctag = country.get("tag")
        cname = country.get("name")
        if not isinstance(ctag, str) or not isinstance(cname, str):
            continue
        key = _normalize_name_key(cname)
        if not key:
            continue
        # First source wins for ambiguous names.
        country_name_to_tag.setdefault(key, ctag)
    tag_to_primary_culture: dict[str, str] = {}
    for country in country_data:
        tag = country.get("tag")
        culture = country.get("culture")
        if isinstance(tag, str) and isinstance(culture, str) and culture:
            tag_to_primary_culture[tag] = culture
    missing_tags = sorted(tag for tag in formable_data if tag not in known_tags)
    if missing_tags:
        sample = ", ".join(missing_tags[:15])
        suffix = "..." if len(missing_tags) > 15 else ""
        print(
            f"Warning: {len(missing_tags)} formable tags missing from extracted countries: {sample}{suffix}"
        )

    def _build_location_hierarchy_maps(
        node: object,
        current_region: str | None = None,
        current_area: str | None = None,
    ) -> tuple[dict[str, str], dict[str, str]]:
        location_to_area: dict[str, str] = {}
        area_to_region: dict[str, str] = {}

        if isinstance(node, dict):
            for key, value in node.items():
                next_region = current_region
                next_area = current_area
                if isinstance(key, str):
                    if key.endswith("_region"):
                        next_region = key
                    if key.endswith("_area"):
                        next_area = key
                        if next_region:
                            area_to_region[next_area] = next_region
                    if (
                        next_area
                        and isinstance(value, (str, int, float))
                        and isinstance(key, str)
                        and not key.endswith("_area")
                        and not key.endswith("_region")
                    ):
                        location_to_area[key] = next_area
                        if next_region:
                            area_to_region[next_area] = next_region

                child_loc_to_area, child_area_to_region = _build_location_hierarchy_maps(
                    value,
                    current_region=next_region,
                    current_area=next_area,
                )
                location_to_area.update(child_loc_to_area)
                area_to_region.update(child_area_to_region)
        elif isinstance(node, list):
            for item in node:
                if isinstance(item, str):
                    if current_area:
                        location_to_area[item] = current_area
                        if current_region:
                            area_to_region[current_area] = current_region
                else:
                    child_loc_to_area, child_area_to_region = _build_location_hierarchy_maps(
                        item,
                        current_region=current_region,
                        current_area=current_area,
                    )
                    location_to_area.update(child_loc_to_area)
                    area_to_region.update(child_area_to_region)

        return location_to_area, area_to_region

    location_to_area, area_to_region = _build_location_hierarchy_maps(eu5_map_data or {})
    location_to_province = _build_location_to_province_map(eu5_map_data or {})
    area_to_locations: dict[str, list[str]] = {}
    region_to_locations: dict[str, list[str]] = {}
    for loc_key, area_key in sorted(location_to_area.items()):
        area_to_locations.setdefault(area_key, []).append(loc_key)
        region_key = area_to_region.get(area_key)
        if isinstance(region_key, str):
            region_to_locations.setdefault(region_key, []).append(loc_key)
    all_provinces = sorted(set(location_to_province.values()))
    all_areas = sorted(set(area_to_region.keys()) | set(location_to_area.values()))
    all_regions = sorted(set(area_to_region.values()))
    province_set = set(all_provinces)
    area_set = set(all_areas)
    region_set = set(all_regions)

    def _resolve_province_name(raw: object) -> str | None:
        if not isinstance(raw, str):
            return None
        text = raw.strip()
        if text.startswith("province:"):
            text = text[9:]
        candidates = [text]
        if text.endswith("_province"):
            candidates.append(text[: -len("_province")])
            candidates.append(f"{text[: -len('_province')]}_area")
        elif text.endswith("_area"):
            candidates.append(text[: -len("_area")])
            candidates.append(f"{text[: -len('_area')]}_province")
        else:
            candidates.append(f"{text}_province")
            candidates.append(f"{text}_area")
        for candidate in candidates:
            if candidate in province_set:
                return candidate
        return None

    def _resolve_area_name(raw: object) -> str | None:
        if not isinstance(raw, str):
            return None
        text = raw.strip()
        if text.startswith("area:"):
            text = text[5:]
        candidates = [text]
        if text.endswith("_area"):
            candidates.append(text[: -len("_area")])
            candidates.append(f"{text[: -len('_area')]}_region")
        elif text.endswith("_region"):
            candidates.append(text[: -len("_region")])
            candidates.append(f"{text[: -len('_region')]}_area")
        else:
            candidates.append(f"{text}_area")
            candidates.append(f"{text}_region")
        for candidate in candidates:
            if candidate in area_set:
                return candidate
        return None

    def _resolve_region_name(raw: object) -> str | None:
        if not isinstance(raw, str):
            return None
        text = raw.strip()
        if text.startswith("region:"):
            text = text[7:]
        candidates = [text]
        if text.endswith("_region"):
            candidates.append(text[: -len("_region")])
        else:
            candidates.append(f"{text}_region")
        for candidate in candidates:
            if candidate in region_set:
                return candidate
        return None

    def _coerce_area_override(raw: object) -> str | None:
        return _resolve_area_name(raw)

    def _coerce_region_override(raw: object) -> str | None:
        return _resolve_region_name(raw)

    def _scope_from_locations(location_ids: list[int]) -> tuple[str | None, list[str], list[str]]:
        location_keys = [id_to_key.get(pid) for pid in location_ids]
        location_keys = [key for key in location_keys if isinstance(key, str)]
        if not location_keys:
            return None, [], []

        inferred_regions: set[str] = set()
        for key in location_keys:
            area = location_to_area.get(key)
            if not area:
                continue
            region = area_to_region.get(area)
            if region:
                inferred_regions.add(region)

        if inferred_regions:
            return "regions", sorted(inferred_regions), sorted(set(location_keys))
        return "locations", sorted(set(location_keys)), sorted(set(location_keys))

    def _areas_from_locations(location_ids: list[int]) -> list[str]:
        location_keys = [id_to_key.get(pid) for pid in location_ids]
        location_keys = [key for key in location_keys if isinstance(key, str)]
        inferred_areas = {
            area
            for key in location_keys
            for area in [location_to_area.get(key)]
            if isinstance(area, str)
        }
        return sorted(inferred_areas)

    def _provinces_from_locations(location_ids: list[int]) -> list[str]:
        location_keys = [id_to_key.get(pid) for pid in location_ids]
        location_keys = [key for key in location_keys if isinstance(key, str)]
        inferred_provinces = {
            province
            for key in location_keys
            for province in [location_to_province.get(key)]
            if isinstance(province, str)
        }
        return sorted(inferred_provinces)

    def _map_ir_culture(raw: object) -> str | None:
        if not isinstance(raw, str):
            return None
        text = raw.strip()
        if not text:
            return None
        return text if text.startswith("ir_") else f"ir_{text}"

    def _map_ir_culture_group(raw: object) -> str | None:
        if not isinstance(raw, str):
            return None
        text = raw.strip()
        if not text:
            return None
        if text.startswith("ir_"):
            return text
        if text.endswith("_group"):
            return f"ir_{text}_g"
        return f"ir_{text}_g"

    def _map_ir_religion(raw: object) -> str | None:
        if not isinstance(raw, str):
            return None
        text = raw.strip()
        if not text:
            return None
        return text if text.startswith("ir_") else f"ir_{text}"

    blocks = []
    emitted_formable_keys: set[str] = set()
    skipped_unlocalized_tags = 0
    for tag in sorted(formable_data.keys()):
        if tag in disabled_formable_tags:
            continue
        meta = formable_data.get(tag, {})
        manual_override = formable_requirement_overrides.get(tag, {})
        loc_override = formable_localization_overrides.get(tag, {})
        resolved_name = str(loc_override.get("name") or meta.get("name") or "").strip()
        if not resolved_name or resolved_name == tag:
            skipped_unlocalized_tags += 1
            continue
        output_tag = str(formable_alias_target_overrides.get(tag, tag))
        # If a non-base formable duplicates an existing country name, emit it
        # using the original tag_f key as requested.
        if tag not in known_tags and output_tag == tag:
            canonical = country_name_to_tag.get(_normalize_name_key(resolved_name))
            if isinstance(canonical, str) and canonical:
                output_tag = canonical
        formable_key = f"{output_tag}_f"
        if formable_key in emitted_formable_keys:
            continue
        if isinstance(meta.get("scope"), dict) and isinstance(meta.get("potential_lines"), list):
            display_name = str(meta.get("name") or tag)
            blocks.append(f"# {tag} -> {output_tag}: {display_name}")

            level = int(meta.get("level", 2))
            if level < 1:
                level = 1
            if level > 4:
                level = 4

            explicit_fraction = meta.get("required_locations_fraction")
            if isinstance(explicit_fraction, (int, float)) and 0 < float(explicit_fraction) <= 1.0:
                required_fraction = f"{float(explicit_fraction):.2f}".rstrip("0").rstrip(".")
            else:
                required_fraction = "0.75" if level <= 2 else "0.6"

            rule = str(meta.get("rule") or "historical")
            potential_lines = [str(v) for v in meta.get("potential_lines", []) if isinstance(v, str)]
            # Keep curated formables intentionally simple (EU5-style basic blocks).
            allow_lines: list[str] = []
            scope = meta.get("scope") if isinstance(meta.get("scope"), dict) else {}

            lines = [
                f"level = {level}",
                f"required_locations_fraction = {required_fraction}",
                f"rule = {rule}",
                "potential = {",
                *[f"    {line}" for line in potential_lines],
                "}",
                "allow = {",
                *[f"    {line}" for line in allow_lines],
                "}",
                f"name = {output_tag}",
                f"flag = {output_tag}",
                f"adjective = {output_tag}_ADJ",
                f"tag = {output_tag}",
            ]
            if output_tag in known_tags:
                lines.append(f"color = map_{output_tag}")

            for scope_type in ("locations", "provinces", "areas", "regions"):
                values = scope.get(scope_type)
                if not isinstance(values, list):
                    continue
                scope_values = sorted({str(v) for v in values if isinstance(v, str) and v})
                if not scope_values:
                    continue
                lines.append(f"{scope_type} = {{")
                for value in scope_values:
                    lines.append(f"    {value}")
                lines.append("}")

            lines.extend(["form_effect = {", "}"])
            blocks.append((formable_key, lines))
            emitted_formable_keys.add(formable_key)
            blocks.append("")
            continue

        ir_level = int(meta.get("level", 1))
        # Shift IR tiers (1/2/3) to EU5-facing tiers (2/3/4).
        level = min(4, ir_level + 1)
        override_level = manual_override.get("level")
        if isinstance(override_level, int) and 1 <= override_level <= 4:
            level = override_level
        display_name = str(meta.get("name") or tag)
        required_fraction = "0.75" if level <= 2 else "0.6"
        override_fraction = manual_override.get("required_locations_fraction")
        if isinstance(override_fraction, (int, float)) and 0 < float(override_fraction) <= 1.0:
            required_fraction = f"{float(override_fraction):.2f}".rstrip("0").rstrip(".")
        required_provinces = sorted(
            {
                province
                for province in (_resolve_province_name(v) for v in meta.get("required_areas", []))
                if province
            }
        )
        required_areas = sorted(
            {
                area
                for area in (_resolve_area_name(v) for v in meta.get("required_regions", []))
                if area
            }
        )
        required_regions = sorted(
            {
                region
                for region in (_resolve_region_name(v) for v in meta.get("required_regions", []))
                if region
            }
        )
        required_location_ids = sorted(
            {int(pid) for pid in meta.get("required_location_ids", []) if isinstance(pid, int)}
        )
        region_percent = meta.get("required_region_percent", [])
        required_primary_cultures = sorted(
            {
                culture
                for culture in (
                    _map_ir_culture(v) for v in meta.get("required_primary_cultures", [])
                )
                if culture
            }
        )
        required_culture_groups = sorted(
            {
                group
                for group in (
                    _map_ir_culture_group(v) for v in meta.get("required_culture_groups", [])
                )
                if group
            }
        )
        required_religions = sorted(
            {
                religion
                for religion in (
                    _map_ir_religion(v) for v in meta.get("required_religions", [])
                )
                if religion
            }
        )
        required_primary_cultures = sorted(
            set(required_primary_cultures)
            | {
                culture
                for culture in (
                    _map_ir_culture(v)
                    for v in manual_override.get("required_primary_cultures", [])
                )
                if culture
            }
        )
        required_culture_groups = sorted(
            set(required_culture_groups)
            | {
                group
                for group in (
                    _map_ir_culture_group(v)
                    for v in manual_override.get("required_culture_groups", [])
                )
                if group
            }
        )
        required_religions = sorted(
            set(required_religions)
            | {
                religion
                for religion in (
                    _map_ir_religion(v) for v in manual_override.get("required_religions", [])
                )
                if religion
            }
        )
        if region_percent:
            try:
                min_pct = min(float(pct) for _pid, pct in region_percent if pct is not None)
                if 0 < min_pct <= 1.0:
                    required_fraction = f"{min_pct:.2f}".rstrip("0").rstrip(".")
            except Exception:
                pass
            for pid, _pct in region_percent:
                if isinstance(pid, int):
                    loc_key = id_to_key.get(pid)
                    if not loc_key:
                        continue
                    area = location_to_area.get(loc_key)
                    region = area_to_region.get(area) if area else None
                    if area and area in all_areas and area not in required_areas:
                        required_areas.append(area)
                    if region and region in all_regions and region not in required_regions:
                        required_regions.append(region)

        blocks.append(f"# {tag} -> {output_tag}: {display_name}")
        potential_lines: list[str] = []
        culture_conditions = (
            [f"culture = culture:{culture}" for culture in required_primary_cultures]
            + [
                f"culture = {{ has_culture_group = culture_group:{group} }}"
                for group in required_culture_groups
            ]
        )
        if len(culture_conditions) == 1:
            potential_lines.append(culture_conditions[0])
        elif len(culture_conditions) > 1:
            potential_lines.append("OR = {")
            for cond in culture_conditions:
                potential_lines.append(f"    {cond}")
            potential_lines.append("}")

        if len(required_religions) == 1:
            potential_lines.append(f"religion = religion:{required_religions[0]}")
        elif len(required_religions) > 1:
            potential_lines.append("OR = {")
            for religion in required_religions:
                potential_lines.append(f"    religion = religion:{religion}")
            potential_lines.append("}")

        if not potential_lines:
            fallback_culture = tag_to_primary_culture.get(tag) or tag_to_primary_culture.get(
                output_tag
            )
            if isinstance(fallback_culture, str) and fallback_culture:
                potential_lines.append(f"culture = culture:{fallback_culture}")

        scope_type = None
        scope_values: list[str] = []
        override_locations = [
            v for v in manual_override.get("locations", []) if isinstance(v, str)
        ]
        override_provinces = sorted(
            {
                province
                for province in (
                    _resolve_province_name(v) for v in manual_override.get("provinces", [])
                )
                if province
            }
            | {
                province
                for province in (
                    _resolve_province_name(v) for v in manual_override.get("areas", [])
                )
                if province
            }
        )
        override_areas = sorted(
            {
                area
                for area in (_coerce_area_override(v) for v in manual_override.get("areas", []))
                if area
            }
            | {
                area
                for area in (_coerce_area_override(v) for v in manual_override.get("regions", []))
                if area
            }
        )
        override_regions = sorted(
            {
                region
                for region in (
                    _coerce_region_override(v) for v in manual_override.get("regions", [])
                )
                if region
            }
        )
        inferred_areas_from_locations = _areas_from_locations(required_location_ids)
        inferred_provinces_from_locations = _provinces_from_locations(required_location_ids)
        if override_locations:
            scope_type, scope_values = "locations", sorted(set(override_locations))
        elif override_provinces:
            scope_type, scope_values = "provinces", sorted(set(override_provinces))
        elif override_areas:
            scope_type, scope_values = "areas", sorted(set(override_areas))
        elif override_regions:
            scope_type, scope_values = "regions", sorted(set(override_regions))
        elif required_provinces:
            scope_type, scope_values = "provinces", sorted(set(required_provinces))
        elif required_areas:
            scope_type, scope_values = "areas", sorted(set(required_areas))
        elif required_location_ids and inferred_provinces_from_locations:
            # I:R decision ownership conditions are province-level.
            scope_type, scope_values = "provinces", inferred_provinces_from_locations
        elif required_location_ids and inferred_areas_from_locations:
            scope_type, scope_values = "areas", inferred_areas_from_locations
        elif required_regions:
            scope_type, scope_values = "regions", sorted(set(required_regions))
        elif required_location_ids:
            scope_type, scope_values, _ = _scope_from_locations(required_location_ids)
        else:
            # Keep every formable valid even when no explicit decision requirement was found.
            capital_id = ir_country_capitals.get(tag)
            if capital_id is None:
                capital_id = ir_country_capitals.get(output_tag)
            if capital_id is not None:
                loc_key = id_to_key.get(capital_id)
                if loc_key:
                    scope_type, scope_values = "locations", [loc_key]

        # Keep allow lightweight and rely on EU5 scope+fraction mechanics for ownership gating.
        allow_lines: list[str] = []

        lines = [
            f"level = {level}",
            f"required_locations_fraction = {required_fraction}",
            "rule = historical",
            "potential = {",
            *[f"    {line}" for line in potential_lines],
            "}",
            "allow = {",
            *[f"    {line}" for line in allow_lines],
            "}",
            f"name = {output_tag}",
            f"flag = {output_tag}",
            f"adjective = {output_tag}_ADJ",
            f"tag = {output_tag}",
        ]
        if output_tag in known_tags:
            lines.append(f"color = map_{output_tag}")

        if scope_type and scope_values:
            lines.append(f"{scope_type} = {{")
            for value in scope_values:
                lines.append(f"    {value}")
            lines.append("}")

        lines.extend(
            [
                "form_effect = {",
                "}",
            ]
        )
        blocks.append((formable_key, lines))
        emitted_formable_keys.add(formable_key)
        blocks.append("")

    write_blocks(out_path, blocks)
    if skipped_unlocalized_tags:
        print(
            f"Skipped {skipped_unlocalized_tags} formables with unresolved localisation name (name == tag)."
        )


def write_localisation_files(
    culture_data: list,
    religion_data: list,
    country_data: list,
    character_data: list,
    dynasties: list,
    deity_data: list,
    formable_data: dict[str, dict[str, object]] | None = None,
):
    def _esc_loc(value: object) -> str:
        return str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    def sort_lines(lines: list[str]) -> list[str]:
        """Keep the first line (header) and sort the rest alphabetically."""
        return [lines[0]] + sorted(lines[1:])

    def remove_duplicate_keys(lines: list[str]) -> list[str]:
        """Remove duplicate keys, keeping only the first occurrence."""
        header, *body = lines
        seen_keys = set()
        unique_lines = []
        for line in body:
            key = line.split(":", 1)[0].strip()
            if key not in seen_keys:
                seen_keys.add(key)
                unique_lines.append(line)
        return [header] + unique_lines

    def _collect_block_ids(path: Path) -> list[str]:
        if not path.exists():
            return []
        from .extract_data import parse_tree

        tree = parse_tree(path)
        return [key for key in tree.keys() if isinstance(key, str)]

    def _collect_dialect_ids(path: Path) -> list[str]:
        if not path.exists():
            return []
        from .extract_data import parse_tree

        tree = parse_tree(path)
        dialects: list[str] = []
        for _lang_id, value in tree.items():
            block = value
            if isinstance(block, list) and block:
                block = block[0]
            if not isinstance(block, _pydt.Tree):
                continue
            dialects_block = block.find("dialects")
            if not isinstance(dialects_block, _pydt.Tree):
                continue
            for dialect_id in dialects_block.keys():
                if isinstance(dialect_id, str):
                    dialects.append(dialect_id)
        return dialects

    def _humanize_ir_id(tag: str) -> str:
        base = tag
        if base.startswith("ir_"):
            base = base[3:]
        if base.endswith("_lang"):
            base = base[: -len("_lang")]
        if base.endswith("_family"):
            base = base[: -len("_family")]
        if base.endswith("_dialect"):
            base = base[: -len("_dialect")]

        specials = {
            "indo_aryan": "Indo-Aryan",
            "indo_iranian": "Indo-Iranian",
            "proto_baltic": "Proto-Baltic",
            "proto_germanic": "Proto-Germanic",
            "proto_finnic": "Proto-Finnic",
            "proto_european": "Proto-European",
            "old_chinese": "Old Chinese",
            "old_south_arabian": "Old South Arabian",
            "magadhan_prakrit": "Magadhan Prakrit",
            "pannonian_celtic": "Pannonian Celtic",
            "celtiberian": "Celtiberian",
            "goidelic": "Goidelic",
            "brittonic": "Brittonic",
            "geez": "Geez",
        }
        if base in specials:
            return specials[base]
        return " ".join(word.capitalize() for word in base.split("_"))

    # -------- Cultures --------
    culture_lines = ["l_english:"]
    for group in culture_data:
        culture_lines.append(f'  {group["tag"]}: "{group["name"]}"')
        culture_lines.append(f'  {group["tag"]}_desc: "{group["name_desc"]}"')
        for culture in group["cultures"]:
            culture_lines.append(f'  {culture["tag"]}: "{culture["name"]}"')
    culture_lines = remove_duplicate_keys(sort_lines(culture_lines))

    # -------- Religions --------
    religion_lines = ["l_english:"]
    for religion in religion_data:
        religion_tag = religion["tag"]
        religion_name = religion["name"]
        religion_lines.append(f'  {religion_tag}: "{religion_name}"')
        religion_lines.append(f'  {religion_tag}_ADJ: "{religion_name}"')
        religion_lines.append(f'  {religion_tag}_desc: "{religion["name_desc"]}"')
    for group_tag, group_name in RELIGION_GROUP_NAMES.items():
        religion_lines.append(f'  {group_tag}: "{group_name} Group"')
        religion_lines.append(f'  {group_tag}_ADJ: "{group_name} Group"')
        religion_lines.append(f'  {group_tag}_desc: "{group_name} Group"')
    religion_lines.extend(
        [
            '  ir_unknown_group: "Unknown Group"',
            '  ir_unknown_group_ADJ: "Unknown Group"',
            '  ir_unknown_group_desc: "Fallback group for unmapped religions"',
        ]
    )
    religion_lines = remove_duplicate_keys(sort_lines(religion_lines))

    # -------- Languages & Families --------
    language_lines = ["l_english:"]
    language_ids = sorted(_collect_block_ids(iu_languages / "ir_languages.txt"))
    dialect_ids = sorted(_collect_dialect_ids(iu_languages / "ir_languages.txt"))
    for lang_id in language_ids:
        language_lines.append(f'  {lang_id}: "{_humanize_ir_id(lang_id)}"')
    for dialect_id in dialect_ids:
        language_lines.append(f'  {dialect_id}: "{_humanize_ir_id(dialect_id)}"')
    for family_id in sorted(
        _collect_block_ids(iu_language_families / "ir_language_families.txt")
    ):
        language_lines.append(f'  {family_id}: "{_humanize_ir_id(family_id)}"')
    language_lines = remove_duplicate_keys(sort_lines(language_lines))

    # -------- Countries --------
    country_lines = ["l_english:"]
    for country in country_data:
        country_lines.append(f'  {country["tag"]}: "{country["name"]}"')
        country_lines.append(f'  {country["tag"]}_ADJ: "{country["name_adj"]}"')
    country_lines = remove_duplicate_keys(sort_lines(country_lines))

    # -------- Formables --------
    formable_lines = ["l_english:"]
    formable_desc_lines = ["l_english:"]
    if formable_data:
        country_name_map = {country["tag"]: country["name"] for country in country_data}
        country_adj_map = {country["tag"]: country["name_adj"] for country in country_data}
        emitted_loc_tags: set[str] = set()
        for tag in sorted(formable_data.keys()):
            if tag in disabled_formable_tags:
                continue
            meta = formable_data.get(tag, {})
            loc_override = formable_localization_overrides.get(tag, {})
            output_tag = str(formable_alias_target_overrides.get(tag, tag))
            raw_name = str(meta.get("name") or country_name_map.get(tag) or tag)
            name = str(loc_override.get("name") or raw_name).strip()
            if name == tag:
                continue
            if output_tag in emitted_loc_tags:
                continue
            raw_adj = loc_override.get("adj") or meta.get("adj")
            if isinstance(raw_adj, str) and raw_adj.strip():
                adj = raw_adj.strip()
            else:
                adj = str(country_adj_map.get(output_tag) or country_adj_map.get(tag) or name)
            formable_lines.append(f'  {output_tag}: "{_esc_loc(name)}"')
            formable_lines.append(f'  {output_tag}_ADJ: "{_esc_loc(adj)}"')
            # EU5-style aliases for formable IDs referenced as TAG_f in UI/scripts.
            formable_lines.append(f'  {output_tag}_f: "{_esc_loc(name)}"')
            formable_lines.append(f'  {output_tag}_f_ADJ: "{_esc_loc(adj)}"')
            desc = meta.get("desc")
            if isinstance(desc, str) and desc.strip():
                formable_desc_lines.append(f'  {output_tag}_f_desc: "{_esc_loc(desc)}"')
            emitted_loc_tags.add(output_tag)
    formable_lines = remove_duplicate_keys(sort_lines(formable_lines))
    formable_desc_lines = remove_duplicate_keys(sort_lines(formable_desc_lines))

    # -------- Characters --------
    character_lines = ["l_english:"]
    character_lines.extend(f'  {c["name_tag"]}: "{c["name"]}"' for c in character_data)
    character_lines.extend(
        f'  {c["nickname_tag"]}: "{c["nickname"]}"'
        for c in character_data
        if c.get("nickname")
    )
    character_lines = remove_duplicate_keys(sort_lines(character_lines))

    # -------- Dynasties --------
    dynasty_lines = ["l_english:"]
    for d in dynasties:
        dynasty_lines.append(f'  {d["tag"]}: "{d["name"]}"')
    dynasty_lines = remove_duplicate_keys(sort_lines(dynasty_lines))

    # -------- Gods --------
    god_lines = ["l_english:"]
    for deity in deity_data:
        deity_tag = deity.get("tag")
        if not deity_tag:
            continue
        name = deity.get("name") or deity_tag
        god_lines.append(f'  {deity_tag}: "{name}"')
        god_lines.append(f'  worship_{deity_tag}: "{name}"')
    god_lines = remove_duplicate_keys(sort_lines(god_lines))

    # -------- Write Files --------
    write_blocks(iu_localisation / "ir_cultures_l_english.yml", culture_lines)
    write_blocks(iu_localisation / "ir_religions_l_english.yml", religion_lines)
    write_blocks(
        iu_localisation / "cultural_and_languages_l_english.yml", language_lines
    )
    write_blocks(iu_localisation / "ir_countries_l_english.yml", country_lines)
    write_blocks(iu_localisation / "ir_formables_l_english.yml", formable_lines)
    if len(formable_desc_lines) > 1:
        write_blocks(
            iu_localisation / "ir_formable_countries_l_english.yml",
            formable_desc_lines,
        )
    write_blocks(iu_localisation / "ir_characters_l_english.yml", character_lines)
    write_blocks(iu_localisation / "ir_dynasties_l_english.yml", dynasty_lines)
    write_blocks(iu_localisation / "ir_gods_l_english.yml", god_lines)


def write_coa_file(coa_data: _pydt.Tree):
    write_blocks(iu_prescripted_coa, coa_data)


def _build_location_to_province_map(tree) -> dict:
    """Build a mapping from location -> province key by walking the eu5 map tree.

    The tree is a nested dict/Tree structure where the smallest keys are location
    identifiers and their parent is the province (the second-smallest tier).
    """
    mapping: dict = {}

    def walk(node, parent=None):
        # pyradox.Tree behaves like dict
        if isinstance(node, (_pydt.Tree, dict)):
            for k, v in node.items():
                if isinstance(v, (_pydt.Tree, dict)):
                    # k is a grouping key (could be province or higher); recurse
                    walk(v, k)
                elif isinstance(v, list):
                    # list of scalar locations or subtrees
                    for item in v:
                        if isinstance(item, (_pydt.Tree, dict)):
                            walk(item, k)
                        else:
                            mapping[str(item)] = k
                else:
                    # leaf value: k is likely a location name, parent is province
                    mapping[str(k)] = parent if parent is not None else k
        elif isinstance(node, list):
            for item in node:
                walk(item, parent)

    walk(tree, None)
    return mapping


def audit_country_locations(
    ten_countries_data: dict,
    country_data: list,
    eu5_map_data,
) -> None:
    """
    Audit own_control_core locations and capitals after writing 10_countries.

    Reports:
    - locations assigned to multiple country tags (only valid locations)
    - locations not present in the map (unknown)
    - capitals not present in the map (unknown)
    """

    location_to_province = (
        _build_location_to_province_map(eu5_map_data)
        if eu5_map_data is not None
        else {}
    )

    owners: dict[str, set[str]] = defaultdict(set)
    unknown_locations: list[tuple[str, str]] = []
    unknown_capitals: list[tuple[str, str]] = []

    for country in country_data:
        tag = country["tag"]
        base = ten_countries_data.get(tag, {})

        # --- own_control_core ---
        value = base.get("own_control_core", [])
        locations = (
            [] if value is None else value if isinstance(value, list) else [value]
        )

        for loc in locations:
            loc_key = str(loc)
            if loc_key not in location_to_province:
                unknown_locations.append((loc_key, tag))
            else:
                owners[loc_key].add(tag)

        # --- capital ---
        capital = base.get("capital")
        if capital:
            cap_key = str(capital)
            if cap_key not in location_to_province:
                unknown_capitals.append((cap_key, tag))
            else:
                owners[cap_key].add(tag)

    # --- REPORT ---
    conflicts = {loc: tags for loc, tags in owners.items() if len(tags) > 1}

    if not conflicts and not unknown_locations and not unknown_capitals:
        print(
            "Location audit: OK (no conflicts, no unknown locations, no unknown capitals)"
        )
        return

    print("\n=== LOCATION AUDIT REPORT ===")

    if conflicts:
        print("\nLocations assigned to multiple countries:")
        for loc, tags in sorted(conflicts.items()):
            print(f"  {loc}: {', '.join(sorted(tags))}")

    if unknown_locations:
        print("\nUnknown locations (own_control_core):")
        for loc, tag in sorted(unknown_locations):
            print(f"  {loc}: assigned to {tag}")

    if unknown_capitals:
        print("\nUnknown capitals:")
        for loc, tag in sorted(unknown_capitals):
            print(f"  {loc}: capital of {tag}")

    print("\n=== END LOCATION AUDIT ===\n")


def write_blocks_with_comments(
    out_path: Path,
    blocks: List[Tuple[str, List[object]]],
    comment_tags: set[str] | None = None,
    mode: str = "w",
    encoding: str = "utf-8",
    indent_str: str = "    ",
) -> Path:
    if comment_tags is None:
        comment_tags = set()

    def render_block(tag: str, lines: list, level: int = 0) -> list[str]:
        prefix = indent_str * level
        inner_prefix = indent_str * (level + 1)
        output: list[str] = []

        # Check if we need to comment out this entire block
        comment_block = tag in comment_tags

        # Opening line
        open_line = f"{prefix}{tag} = {{"
        if comment_block:
            open_line = "# " + open_line
        output.append(open_line)

        for line in lines:
            if isinstance(line, tuple) and len(line) == 2:
                subtag, sublines = line
                sublines_rendered = render_block(subtag, sublines, level + 1)
                if comment_block:
                    # Prefix every line of sub-block
                    sublines_rendered = [
                        f"# {l}" if not l.startswith("#") else l
                        for l in sublines_rendered
                    ]
                output.extend(sublines_rendered)
            else:
                l = f"{inner_prefix}{line}"
                if comment_block:
                    l = "# " + l if not l.startswith("#") else l
                output.append(l)

        # Closing brace
        close_line = f"{prefix}}}"
        if comment_block:
            close_line = "# " + close_line
        output.append(close_line)

        return output

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open(mode, encoding=encoding) as f:
        for block in blocks:
            if isinstance(block, tuple) and len(block) == 2:
                tag, lines = block
                rendered_lines = render_block(tag, lines, level=0)
                f.write("\n".join(rendered_lines) + "\n")
            else:
                # raw string block
                s = str(block)
                f.write(s)
                if not s.endswith("\n"):
                    f.write("\n")

    print_written("file", out_path)
    return out_path


def write_10_countries(
    ten_countries_data,
    country_data,
    eu5_map_data,
    country_rulers,
    culture_data=None,
    ir_country_locations=None,
    ir_country_capitals=None,
    id_to_key=None,
    location_keys=None,
):
    country_map = {country["tag"]: country for country in country_data}
    blocks = []
    comment_tags = set()

    rank_map = (
        _build_country_rank_map(ir_country_locations, country_data)
        if ir_country_locations is not None
        else {}
    )

    culture_to_group = {}
    if culture_data:
        for group in culture_data:
            group_tag = group.get("tag")
            for culture in group.get("cultures", []):
                culture_to_group[culture.get("tag")] = group_tag

    # build province mapping if provided
    location_to_province = (
        _build_location_to_province_map(eu5_map_data)
        if eu5_map_data is not None
        else {}
    )

    def normalize_value(value):
        if isinstance(value, str):
            v = value.strip()
            if len(v) >= 2 and v[0] == '"' and v[-1] == '"':
                return v[1:-1]
            return v
        return value

    for country in country_data:
        tag = country["tag"]
        country_name = country.get("name", tag)
        government_type = government_map[country_map[tag]["government"]]
        ruler = country_rulers.get(tag)  # optional override

        # --- start from base, preserve everything ---
        base = ten_countries_data.get(tag, {})
        merged = dict(base)  # shallow copy

        # --- own_control_core ---
        ir_locations = None
        if ir_country_locations is not None and id_to_key is not None:
            ir_locations = []
            for pid in ir_country_locations.get(tag, []):
                if pid in id_to_key:
                    loc = id_to_key.get(pid)
                    if loc is None:
                        continue
                    if location_keys is None or loc in location_keys:
                        ir_locations.append(loc)
        if ir_locations is not None:
            locations = ir_locations
        else:
            value = base.get("own_control_core", [])
            locations = (
                [] if value is None else value if isinstance(value, list) else [value]
            )

        if not locations:
            # force inline empty block (keep country enabled)
            merged["own_control_core"] = "{ }"
        else:
            prov_map: dict[str, list] = {}
            used_locations = set()  # track all locations globally

            for loc in locations:
                key = str(loc)
                if key in used_locations:
                    continue  # skip duplicates across provinces
                prov = location_to_province.get(key, "unknown")
                prov_map.setdefault(prov, []).append(key)
                used_locations.add(key)

            own_sublines: list[str] = []
            for prov, locs in sorted(prov_map.items()):
                own_sublines.append(f"# {prov}")
                own_sublines.append(" ".join(locs))

            merged["own_control_core"] = own_sublines

        # --- government (merge, override ruler if exists) ---
        base_government = base.get("government", {})
        if isinstance(base_government, _pydt.Tree):
            base_government = dict(base_government)
        if not isinstance(base_government, dict):
            base_government = {}
        merged_government = dict(base_government)  # copy existing fields

        if ruler:
            merged_government["ruler"] = ruler
        else:
            merged_government["ruler"] = base_government.get("ruler", "random")

        merged_government["type"] = government_type

        # --- include IR-specific starting government reform if available ---
        try:
            ir_gov_key = country_map[tag]["government"]
        except Exception:
            ir_gov_key = None

        if ir_gov_key:
            reform_id = f"ir_{ir_gov_key}"
            raw = merged_government.get("reforms", [])
            normalized = [str(item) for item in ensure_list(raw) if item not in (None, "")]
            normalized.append(reform_id)
            merged_government["reforms"] = _dedupe(normalized)

        merged["government"] = merged_government

        # --- court language ---
        culture_tag = country.get("culture")
        if culture_tag:
            court_language = ir_culture_language_overrides.get(culture_tag)
            if not court_language:
                group_tag = culture_to_group.get(culture_tag)
                if group_tag:
                    court_language = ir_culture_group_language_map.get(group_tag)
            if court_language:
                court_language = _language_to_dialect_id(court_language)
                merged["court_language"] = court_language

        # --- include societal values template based on IR government type ---
        societal_template_keys = {
            "aristocratic_monarchy",
            "despotic_monarchy",
            "stratocratic_monarchy",
            "theocratic_monarchy",
            "aristocratic_republic",
            "democratic_republic",
            "oligarchic_republic",
            "plutocratic_republic",
            "tribal_chiefdom",
            "tribal_federation",
            "tribal_kingdom",
        }

        # --- includes (preserve all, normalize) ---
        raw_include = base.get("include", [])
        include_items = raw_include if isinstance(raw_include, list) else [raw_include]

        if "expl_imperator_rome" not in include_items:
            include_items = ["expl_imperator_rome", *include_items]

        if ir_gov_key in societal_template_keys:
            societal_template = f"ir_{ir_gov_key}"
            if societal_template not in include_items:
                include_items = ["expl_imperator_rome", societal_template] + [
                    x for x in include_items if x != "expl_imperator_rome"
                ]

        merged["include"] = include_items

        # --- simple defaults ---
        merged.setdefault("country_rank", "rank_county")
        if rank_map:
            merged["country_rank"] = rank_map.get(tag, merged["country_rank"])
        merged.setdefault("capital", "REPLACE_ME")

        # --- starting technology level ---
        if "starting_technology_level" not in merged:
            start_level = 2
            if ir_gov_key and ir_gov_key.startswith("tribal_"):
                start_level = 1
            merged["starting_technology_level"] = start_level

        # --- apply IR capital if available ---
        if ir_country_capitals is not None and id_to_key is not None:
            cap_id = ir_country_capitals.get(tag)
            if cap_id is not None:
                cap_key = id_to_key.get(cap_id)
                if cap_key and (location_keys is None or cap_key in location_keys):
                    merged["capital"] = cap_key

        # --- ensure capital is a valid location ---
        if locations:
            cap = merged.get("capital")
            if cap in ("REPLACE_ME", None) or (
                location_keys is not None and cap not in location_keys
            ):
                merged["capital"] = locations[0]

        # --- emit ---
        lines: list = []
        lines.append(f"# {country_name}")

        for key, value in merged.items():
            if key == "include":
                for x in value:
                    lines.append(f'include = "{x}"')

            elif isinstance(value, dict):
                sub = []
                for k, v in value.items():
                    if isinstance(v, list):
                        sub.append((k, v))
                    else:
                        sub.append(f"{k} = {normalize_value(v)}")
                lines.append((key, sub))

            elif isinstance(value, list):
                lines.append((key, value))

            else:
                # strings, numbers, AND inline "{ }"
                lines.append(f"{key} = {normalize_value(value)}")

        blocks.append((tag, lines))

    nested = ("countries", [("countries", blocks)])
    top_line = "current_age = age_1_traditions"

    write_blocks_with_comments(
        iu_setup_start / "10_countries.txt",
        [top_line, nested],
        comment_tags=comment_tags,
    )

    # --- audit pass ---
    audit_country_locations(ten_countries_data, country_data, eu5_map_data)


def write_05_characters(five_characters_data, character_data):
    # --- helpers ---
    char_by_id = {c["id"]: c for c in character_data}
    character_map = {c["id"]: c["tag"] for c in character_data}

    # --- build parent dependencies ---
    deps = defaultdict(set)
    for c in character_data:
        cid = c["id"]
        if c.get("father"):
            deps[cid].add(c["father"])
        if c.get("mother"):
            deps[cid].add(c["mother"])

    # --- topological sort (parents first) ---
    indeg = {c["id"]: 0 for c in character_data}
    for child, parents in deps.items():
        indeg[child] += len(parents)

    queue = [cid for cid, d in indeg.items() if d == 0]
    topo_order = []

    while queue:
        cid = queue.pop(0)
        topo_order.append(cid)
        for c, parents in deps.items():
            if cid in parents:
                indeg[c] -= 1
                if indeg[c] == 0:
                    queue.append(c)

    # --- enforce spouse adjacency ---
    used = set()
    final_order = []

    for cid in topo_order:
        if cid in used:
            continue

        c = char_by_id[cid]
        spouse = c.get("spouse")

        if spouse and spouse not in used:
            final_order.append(cid)
            final_order.append(spouse)
            used.add(cid)
            used.add(spouse)
        else:
            final_order.append(cid)
            used.add(cid)

    # --- emit blocks ---
    blocks = []
    comment_tags = set()
    spouse_emitted = set()

    for cid in final_order:
        character = char_by_id[cid]

        tag = character["tag"]
        name = character["name"]
        name_tag = character["name_tag"]
        dynasty = character["dynasty_tag"]

        # --- start from base, preserve everything ---
        base = five_characters_data.get(tag, {})
        merged = dict(base)

        if name_tag:
            merged["first_name"] = f"{{ name = {name_tag} }}"
        else:
            merged["first_name"] = "random"

        if dynasty:
            merged["dynasty"] = dynasty

        # --- relations ---
        if character.get("father"):
            merged["father"] = character_map[character["father"]]
        if character.get("mother"):
            merged["mother"] = character_map[character["mother"]]

        if character.get("spouse") and cid not in spouse_emitted:
            merged["spouse"] = character_map[character["spouse"]]
            spouse_emitted.add(character["spouse"])

        # --- attributes ---
        if character.get("culture"):
            merged["culture"] = character["culture"]
        if character.get("female"):
            merged["female"] = "yes"
        if character.get("religion"):
            merged["religion"] = character["religion"]

        merged["tag"] = character["country"]
        merged["birth_date"] = character["birth_date"]
        if "death_date" in character and character["death_date"]:
            merged["death_date"] = character["death_date"]

        if character.get("nickname_tag"):
            merged["nickname"] = character["nickname_tag"]

        # --- emit ---
        lines = []
        comment = f"# {name}"
        if dynasty:
            comment += dynasty
        lines.append(comment)

        for key, value in merged.items():
            if isinstance(value, dict):
                sub = [f"{k} = {v}" for k, v in value.items()]
                lines.append((key, sub))
            elif isinstance(value, list):
                lines.append((key, value))
            else:
                lines.append(f"{key} = {value}")

        blocks.append((tag, lines))

    nested = ("character_db", blocks)

    write_blocks_with_comments(
        iu_setup_start / "05_characters.txt",
        [nested],
        comment_tags=comment_tags,
    )


def write_04_dynasties(four_dynasties_data: dict, dynasties_data: list[dict]):
    blocks = []
    comment_tags = set()

    # --- merge new dynasties into existing dict ---
    for dynasty in dynasties_data:
        dynasty_tag = dynasty["tag"]

        # start from existing base if present
        base = four_dynasties_data.get(dynasty_tag, {})
        merged = dict(base)

        # override/add new fields
        merged.update(dynasty)

        # convert 'name' to single-level nested like default_dynasty
        merged["name"] = f"{{ name = {dynasty_tag} }}"

        # store back
        four_dynasties_data[dynasty_tag] = merged

    # --- emit all dynasties ---
    for dynasty_tag in sorted(four_dynasties_data):
        dynasty = four_dynasties_data[dynasty_tag]
        lines = []

        for key, value in dynasty.items():
            if key == "tag":
                continue  # skip tag entirely
            elif isinstance(value, dict):
                sub = [f"{k} = {v}" for k, v in value.items()]
                lines.append((key, sub))
            elif isinstance(value, list):
                lines.append((key, value))
            else:
                # simple scalar, including name
                lines.append(f"{key} = {value}")

        blocks.append((dynasty_tag, lines))

    nested = ("dynasty_manager", blocks)

    write_blocks_with_comments(
        iu_setup_start / "04_dynasties.txt",
        [nested],
        comment_tags=comment_tags,
    )


def write_12_diplomacy(twelve_diplomacy_data: dict, diplomatic_relationships: list):
    blocks = []
    comment_tags = set()

    for relationship in diplomatic_relationships:
        attrs = " ".join(
            f"{key} = {value}" for key, value in relationship.items() if key != "tag"
        )
        block = f"{relationship['tag']} = {{ {attrs} }}"
        blocks.append(block)

    nested = ("diplomacy_manager", blocks)

    write_blocks_with_comments(
        iu_setup_start / "12_diplomacy.txt",
        [nested],
        comment_tags=comment_tags,
    )


def write_15_international_organizations(
    fifteen_international_organizations_data: dict,
    international_organizations: list,
):
    blocks = []
    comment_tags = set()

    for io in international_organizations:
        type = io["type"]
        members = " ".join(io["members"])
        block = (
            "add_international_organization",
            [f"type = {type}", f"members = {{ {members} }}"],
        )
        blocks.append(block)

    nested = ("international_organization_manager", blocks)

    write_blocks_with_comments(
        iu_setup_start / "15_international_organizations.txt",
        [nested],
        comment_tags=comment_tags,
    )
